### ISSUE TITLE
Interface exception message "Set particle position first." misleading

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#1214]
I did not check all of them, but some of the errors that say _"Set particle position first"_ thrown on failed particle property changes have nothing to do with the positions. We should run through the `set_particle..() `methods in particle_data.cpp and give meaningful error messages. Most of them are _"Particle with ID xyz does not exists"_ I think.

**Comment by RudolfWeeber** [comment]
On Fri, Jun 30, 2017 at 01:38:14PM +0000, KonradBreitsprecher wrote:
> I did not check all of them, but some of the errors that say _"Set particle position first"_ thrown on failed particle property changes have nothing to do with the positions. We should run through the `set_particle..() `methods in particle_data.cpp and give meaningful error messages. Most of them are _"Particle with ID xyz does not exists"_ I think.
My understanding is the following:
s.part[i].anything for i=invalid id
raises an exception that the particle does not exists. This is thrown by the __getitem__ of the ParticleList.

When adding a new particle, the Python interface will always set the position first, because only then it is determined, which node has the particle. This was also necessary in the tcl interface.

How did you cause the "set position first" error?

**Comment by KonradBreitsprecher** [comment]
I got this while setting an exclusion to a non-existing particle id. Could not find it elsewhere other than accessing a invalid id though. The node argument makes sense, but maybe something like "Particle id invalid or position not set" would be more clear.

**Comment by KonradBreitsprecher** [comment]
Closed via #1652
