### ISSUE TITLE
Use python unit test framework

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1229]
for integration tests instead of ctest to better handle skipped tests.

**Comment by RudolfWeeber** [comment]
I had a look. This seems to be non-trivial, since
pypresso -m unittest discover --pattern=*.py
runs the tests in a single Python process. However, espresso's System class can only be instanced once per process, due to the globals in Espresso.
One could probably write a custom testrunner, which uses a new process for every test case, but its probably not worth the effort.
