### ISSUE TITLE
Segmentation fault due to std::vector in ParticleProperties

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1327]
The following minimal example produces a segmentation fault
```python
import espressomd
s = espressomd.System()
s.part.add(pos=[0,0,0])
s.part.writevtk("abc.vtk")
```
but only with `maxset.hpp` and running in `gdb`.  The debugger points to these lines in `ParticleProperties` which were introduced in #1201 https://github.com/espressomd/espresso/blob/ee9bbbc4576713d082b90a8002ad4751e3b31940/src/core/particle_data.hpp#L212-L215
In the destructor of `ParticleProperties` their allocator segfaults on freeing memory (why?).

Here is a full backtrace https://gist.github.com/anonymous/a563be9c515b2a1e3913a1ff68d9dcc3

I'm building on Ubuntu 16.04 with compilers and libraries from the official repos.

**Comment by hmenke** [comment]
I have tried adding a default constructor to `ParticleProperties`
```cpp
ParticleProperties() : anchors(0), anchors_out(0) {};
```
to make sure that the vectors do not have a garbage length but it still fails.

**Comment by fweik** [comment]
The cause is the memove in mpi_recv_part for local particles. The other properties that contain heap memory are handled explicitly, the new stuff is not. I've got a branch where this is solved in a general way (by implementing a proper copy operator for Particle).

**Comment by jdegraaf** [comment]
So, can we conclude that the issue is not the way the tutorials are implemented, hence, the pull request for new tutorials can be put through? We'll have to 

1. double check the tutorials for the school
2. make a new Active_Matter git label

at some point in the future anyway. And, as far as I gather, the first point can only be done once the above problem is fixed. Still, from a review point, all of the tutorials put together by Henri look convincing and I expect the last one to run smoothly too, whenever the bug is fixed.

**Comment by jdegraaf** [comment]
Oops, sorry, wrong thread...
