### ISSUE TITLE
Too many travis checks?

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1388]
IS  env: myconfig=maxset image=ubuntu-cuda make_check=false, os: linux
still needed, now that we have cuda testing at icp?
And what is the purpose of
 env: myconfig=nocheck-maxset make_check=false, os: linux

**Comment by mkuron** [comment]
The CUDA build is now mostly useful for running on people's own repositories so that they can find errors earlier, before posting a pull request.

The nocheck-maxset contains (or contained in the past) options that were not compatible with each other. Everything compiles, but some tests cannot pass. So this test mainly serves to ensure that some of the more obscure code in Espresso remains compilable, even if it cannot be tested.

**Comment by hmenke** [comment]
Actually, `nocheck-maxset.hpp` and `maxset.hpp` have diverged.  The `nocheck-maxset.hpp` is missing the switches
```cpp
#define REACTION_ENSEMBLE
#define ENGINE
#define EK_ELECTROSTATIC_COUPLING
#define EWALD_GPU
#define TWIST_STACK
#define HYDROGEN_BOND
#define FLATNOISE
```
The main difference is that `nocheck-maxset.hpp` defines all of the `_DEBUG` flags.  I'm very unsure how useful that is at all if we do not run tests with this.  The `_DEBUG` flags only introduce runtime checking, so it's not so useful to just compile and never run.  One might argue that this way we ensure that the runtime checking is compilable but then we could also just use a static syntax checker, e.g. GCC with `-fsyntax-only` (which is much faster).

**Comment by fweik** [comment]
This is to ensure that the all the debug messages build, because they are macroed out in the other configs.
