### ISSUE TITLE
Introduce interface compatibility level check at instancing of System()

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1394]
So that users get warned when the script was written for an other Es version

**Comment by hmenke** [comment]
I don't think I get what you mean.  We could introduce a version string, like
```python
system = espressomd.System(version="4.0")
```
but we'd still have to manually bump the version number which we then hard-code in the interface.  We also might run into problems because we would have to decide when to bump the version number and moreover, we would probably need some sort of compatibility layer, such that people running 4.1 can still use their 4.0 scripts.  That is not necessarily a bad thing and is even favourable from a software architecture point of view but I wonder whether we really want to invest effort into this.

**Comment by mkuron** [comment]
In an ideal world, the interface is stable and versioning is not required. The Tcl interface was actually pretty good in that regard. If incompatible changes are required, the old function needs to be deprecated (throw a warning or an error) and a new one with a different name needs to be added.

**Comment by RudolfWeeber** [comment]
> In an ideal world, the interface is stable and versioning is not required. The Tcl interface was actually pretty good in that regard. 
>If incompatible changes are required, the old function needs to be deprecated (throw a warning or an error) and a new one with a different name needs to be added.
This not being an ideal world...
The fact that we had to keep the tcl interface stable prevented us from making significant changes to the core and also eventually fix sub-optimal interface design choices.
We'd have more freedom in the future, if we made the version dependence explicit
s=System(version="4.0")
or
espressomd.compatibility("4.0")
As we release quite rarely, deprecation warnings would force very large lags upon us. (time of 2 releases until change can take effect).
Also, often, the output of existing simulation scripts is not actually looked at when they are re-run later.

**Comment by RudolfWeeber** [comment]
>moreover, we would probably need some sort of compatibility layer, such that people running 4.1 can still use their 4.0 scripts.  That is not necessarily a bad thing and is even favourable from a software architecture point of view but I wonder whether we really want to invest effort into this.
I would not plan for a compatibility layer. Instead, point people to a list with the interface changes (if any). They can then check their scripts and set the current version string.
