### ISSUE TITLE
Build and deploy tutorials in CI

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1487]
The job on gitlab ci that builds and deploys sphinx and doxygen should also do the same with the tutorial pdf's.

**Comment by jngrad** [comment]
Deploying the pdf's should not be too difficult. However, since this issue was opened, most of the tutorials have been rewritten as Jupyter notebooks. These need to be run in pypresso, which takes quite some time and requires some form of pre-processing to remove long or infinite loops and calls to the visualizers. I've been working on a solution to that problem using a more elaborate version of an already available pre-processing script [importlib_wrapper.py](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/importlib_wrapper.py).

**Comment by jngrad** [comment]
Once we get the pdf's deployed, we might as well remove them from the source code. They always get outdated.

**Comment by jngrad** [comment]
Update: to build PDF's, we need texlive installed. I tried `texlive` (240 MB), `texlive-latex-extra` (404 MB) and `texlive-full` (4.7 GB) and only the latter works. When using the formers, some essential packages are missing (e.g. TikZ) and cannot be installed via the texlive package manager due to a difference of year; I tried pinning the 2017 version of the texlive archive maintained on TUG, only to get error messages (see trace below). Installing them with wget is too time-consuming.
@mkuron could an extra 4.7 GB of data in the `cuda-tutorials` image cause performance issue?

```
$ tlmgr install tikz
(running on Debian, switching to user mode!)
tlmgr: Remote repository is newer than local (2017 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
$ tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
(running on Debian, switching to user mode!)
tlmgr: setting default package repository to ftp://tug.org/historic/systems/texlive/2017/tlnet-final
$ tlmgr install tikz
(running on Debian, switching to user mode!)
/usr/bin/tlmgr: open tlpdb(ftp://tug.org/historic/systems/texlive/2017/tlnet-final/tlpkg/texlive.tlpdb) failed:  at /usr/share/texlive/tlpkg/TeXLive/TLPDB.pm line 362.
$ tlmgr install revtex4-1
(running on Debian, switching to user mode!)
tlmgr: main database at ftp://tug.org/historic/systems/texlive/2017/tlnet-final is not signed
```

**Comment by mkuron** [comment]
I wouldn’t recommend increasing the image size like that. How about installing a minimal texlive 2019 with the needed packages? There is a ppa at https://launchpad.net/~jonathonf/+archive/ubuntu/texlive.

**Comment by jngrad** [comment]
Cool! With this PPA, the image size only increases by 240 MB (177 MB for `texlive-latex-recommended` and the rest for required packages). This increases the coupling between the docker and espresso repos though (third block below), so we should refrain ourselves from creating new tutorials in LaTeX:
```bash
# install TeXlive 2019 from a PPA
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y ppa:jonathonf/texlive \
    && apt-get update \
    && apt-get install -y --no-install-recommends texlive-latex-recommended texlive-fonts-recommended

RUN useradd -m espresso
USER 1000

# install extra LaTeX packages locally
RUN tlmgr init-usertree \
    && tlmgr install pgf tikz-3dplot revtex units mhchem chemgreek todonotes upquote framed subfigure cleveref \
    && tlmgr install lm stmaryrd 2>&1 || : \
    && updmap -user

```
