### ISSUE TITLE
Base class for python tests

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1491]
We should add a base class for the python tests that creates a system and sets the espresso and numpy seeds.

**Comment by jngrad** [comment]
Introducing a new class `TestCaseSystem` deriving from `ut.TestCase` that sets up an espresso `System` reduces the flexibility of the integration tests:
* the class-level `system` handle is no longer available in the test class
   - many Python tests need to set up additional attributes like the time step, box_l, periodicity and skin, which cannot be done with `system.X` anymore, nor with `self.system` in `setUp()` since changing these internal attributes between two tests can be problematic, which leaves us with `cls.system` in the classmethod `setUpClass()`. This is inconvenient since this classmethod should be used as rarely as possible, and can cause a race condition with the `reaction_ensemble.WangLandauReactionEnsemble` and `reaction_ensemble.ReactionEnsemble` classes which need to be instantiated after the `System` class.
   - objects added into the list of actors need to be moved to `setUpClass()`
   - `@ut.skipIf(system.X)` cannot be used in `dawaanr-*.py` tests
   - automatically-generated tests (e.g. via `generate_test_for_class()` in `magnetostaticInteractions.py`) require the `system` as first argument
* inheritance
   - inheritance becomes an issue when the `system` is instantiated in a class that derives from `object` instead of `ut.TestCase`, which is then used in derived classes with multiple inheritance (e.g. most `lb_*.py` tests), because we can only have one system
   - `setUpClass()` in classes deriving from a `TestCaseSystem` needs a call to `super()`
   - the `System` class is sometimes instantiated outside the unittest class (e.g. `stress.py`)

Branch [jngrad:fix-1491](https://github.com/espressomd/espresso/compare/5b88304...jngrad:fix-1491?expand=1&w=1) shows an implementation using a `TestCaseSystem` class based on `ut.TestCase` that sets the system and its seed, and the numpy seed. Only 92 files out of 128 could be modified with `uts.TestCaseSystem` without too much trouble. The gain in lisibility is not significant, we only lost 33 lines of code (after excluding the header in `unittest_system.py`). The remaining 36 files would probably require more lines of code than they currently have to comply with the new `TestCaseSystem` class.

@fweik Although I like the idea, after implementing it, my impression is that we are only adding a new layer of complexity.

**Comment by RudolfWeeber** [comment]
I suppose, what can be done at present is achievd by @jngrad's recent PR.

**Comment by jngrad** [comment]
Offline discussion with @RudolfWeeber: the PR in question (#2888) already simplified the tests a lot and little can be done to automatize them further, as shown in my failed attempt in the message above.

I'd add that espresso might eventually be fully contained in a single class, allowing multiple instances of `system` in the same script. This would solve some of the issues listed above, but even then, the first point about the class-level handle being no longer available would remain a major barrier within our current `unittest` framework.
