### ISSUE TITLE
mdlc (dipolar layer correction) test needs to be checked

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1569]
The fact that the test did not fail in spite of the bug removed in #1568 suggests that the test didn't test the method sufficiently. The test data uses sqrt(3) as dipole moment, so the unintended cast to int in the calculation of the total dipole moment should have made a difference.

**Comment by jngrad** [comment]
Also the test (`dipolar_mdlc_p3m_scafacos_p2nfft.py`) could be modernized:

- remove print statements conveying the same information as one of the assertions
- use `float(np.genfromtxt())` instead of python2-style file open
- deduce `n_particle` from the size of the particle array loaded from file
- instantiate all particles at once with numpy slicing
- maybe replace the duplicated code logic for `err_*` variables by a class static method to calculate the standard error or the mean from two input variables (the sample size can be deduced from those inputs, no need to involve `data.shape[0]`)

**Comment by jngrad** [comment]
The proposed improvements to `dipolar_mdlc_p3m_scafacos_p2nfft.py` have been applied in 5ddc3f0178878.
