### ISSUE TITLE
Compiling in dpd slows down lj liquid by 20-25%

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1585]
Default myconfig + DPD, 20k particles on 2 cpus, phi=0.5, skin tuned
5.8 vs 4.7 ms

Most likely cause is the fact that the dpd pair force is not inlined and does not have an early exit if dpd is off.

**Comment by hmenke** [comment]
I suspect this one:
https://github.com/espressomd/espresso/blob/d2ec3e4de53a83eccc4e37dc52872227dcbdadc5/src/core/initialize.cpp#L695-L700

but guarding the DPD interaction is not a bad idea either.  Just do
```cpp
#ifdef DPD
  if (ia_params->dpd_r_cut > 0)
      add_dpd_pair_force(p1, p2, ia_params, d, dist, dist2);
#endif
```
instead of the current
https://github.com/espressomd/espresso/blob/d2ec3e4de53a83eccc4e37dc52872227dcbdadc5/src/core/forces_inline.hpp#L332-L334

**Comment by RudolfWeeber** [comment]
> I suspect this one:
> https://github.com/espressomd/espresso/blob/d2ec3e4de53a83eccc4e37dc52872227dcbdadc5/src/core/initialize.cpp#L695-L700
That, as I understand it, only activates ghost velocities if dpd is
actually turned on

**Comment by fweik** [comment]
I think 
```c++
#ifdef DPD
  if (thermo_switch & THERMO_DPD)
      add_dpd_pair_force(p1, p2, ia_params, d, dist, dist2);
#endif
```
is more branch prediction friendly. I'll try that.

**Comment by hmenke** [comment]
True, it is more branch-prediction-friendly but at the same time prohibits using the DPD interaction without the DPD thermostat.

**Comment by fweik** [comment]
The dpd interaction does only work if the dpd thermostat is turned on anyway. This is needed so that it obeys the global temperature. It would not be hard though to factor out a friction interaction that can be used on its own and is used by dpd, so I think I'll go with my proposed solution as long there is no customer for a stand alone friction ia.
