### ISSUE TITLE
Incude _GLIBCXX_DEBUG flag in default debug flags for CXX compiler

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1671]

**Comment by hmenke** [comment]
No, because it's not portable.  It only works with GNU libstdc++ and probably not even on all versions.

**Comment by mkuron** [comment]
Actually, it's not such a bad idea. libc++ has `_LIBCPP_DEBUG`. Range checks in debug mode can be quite useful.

Are there any other C++ standard libraries worth supporting? Boost has a [list](http://www.boost.org/doc/libs/1_60_0/libs/predef/doc/html/predef/reference/boost_lib_library_macros.html), but the only ones on there that do C++11 are Dinkumware (included in Microsoft Visual C++) and Modena (in the Cray compiler). Since we don't do development on these platforms, there's no need to bother with them.

**Comment by KaiSzuttor** [comment]
Maybe we should not close issues before we are sure what to do with it.

**Comment by fweik** [comment]
Portability would only be an issue if there are standard library implementations other than gcc's that use _GLIBCXX_DEBUG, which is very unlikely. Identifiers beginning with an underscore followed by a capital letter are reserved for the implementation, so 3rd party code is never allowed to use them. So I'm in favor of this. For the Espresso internal containers like Utils::List range-checking is also enabled in DEBUG builds.
