### ISSUE TITLE
Running make check in Debug mode reveals quite some problems

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#1677]
The output is too long to be copied here.

**Comment by hmenke** [comment]
Which debug flags?  Like simply `cmake -DCMAKE_BUILD_TYPE=Debug ..`?

**Comment by jonaslandsgesell** [comment]
Yes exactly. If you run make check but with the debug build, quite a lot segfaults are generated. What is strange though is that running e.g. the cellsystem.py manually (without calling make check) is fine (while this testcase crashes when called through make check).

**Comment by hmenke** [comment]
Hm, maybe setting the default build type to `Release` is not so smart.
https://github.com/espressomd/espresso/blob/4437db76a059d9627197477133953a7e6bacfd0f/CMakeLists.txt#L49-L51

**Comment by hmenke** [comment]
The `cellsystem.py` testcase is run in parallel by `make check`.  Did you also run it in parallel manually?
https://github.com/espressomd/espresso/blob/4437db76a059d9627197477133953a7e6bacfd0f/testsuite/CMakeLists.txt#L26

**Comment by jonaslandsgesell** [comment]
Thanks, running the testcase manually in parallel reproduces the segfaults.

**Comment by fweik** [comment]
Debug builds are considerably slower, this is why this is not default. We could do the testing on gitlab with Debug builds though.

**Comment by mkuron** [comment]
How much slower are Debug builds of Espresso? If it’s 2-3 orders of magnitude, like I‘ve seen in other software, we couldn’t even put them on Gitlab CI because it‘d take hours to run all tests. Maybe we can do RelWithDebugInfo builds? They contain debugging symbols and assertions, but are built with `-O2`.

**Comment by fweik** [comment]
We're already running only with -O1/-Og because of codecov, so the difference is not that big. The default is Release because of the users, not because of CI.

**Comment by fweik** [comment]
As for the segfaults, these are caused because boost is not build with _GLIBCXX_DEBUG, but espresso is. (c.f. https://lists.boost.org/boost-build/2011/07/25237.php). So we either have to use our own boost for testing or disable _GLIBCXX_DEBUG. (The deeper reason is that the memory layout of the STL structures is chagned by the option, which messes up serialization if the debug option is not used consistently.")

**Comment by RudolfWeeber** [comment]
> As for the segfaults, these are caused because boost is not build with _GLIBCXX_DEBUG, but espresso is. (c.f. https://lists.boost.org/boost-build/2011/07/25237.php). So we either have to use our own boost for testing or disable _GLIBCXX_DEBUG. (The deeper reason is that the memory layout of the STL structures is chagned by the option, which messes up serialization if the debug option is not used consistently.") 
In that case, I'd rather not use a custom boost for testing.
* complicates our test environment
* and we should test Espresso with the boost versions deployed with the
  distros that people are using
