### ISSUE TITLE
Add static analysis to CI

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1681]
This should be done on gitlab, since this takes some time. Cmake has to be run first, to get the compile commands, so we can split the jobs in multiple parts, forwarding the buid dir as artifact between stages for each config, starting with cmake, then static anlysis, build and finaly running the tests. This would also give more detailed and potentially quicker feedback in case of failure. Tool-wise I'd use clang-tidy for this, as this seems to have the most momentum at the moment and has so MPI related analysis in newer releases.

**Comment by mkuron** [comment]
>  to get the compile commands

It shouldn't be necessary to extract the compile commands. Something like this should do to run Clang static analysis right through CMake:
```
scan-build cmake ..
scan-build make
```

> forwarding the buid dir as artifact between stages for each config, starting with cmake, then static anlysis, build and finaly running the tests

I don't think this is a good idea. It would split every compiler and configuration into four separate build steps, which would make the pipelines page very messy and actually waste significant amounts of time because the same Docker image might need to be downloaded multiple times and the Git repository is re-cloned every time.
