### ISSUE TITLE
Test pickle checkpointing

### ISSUE THREAD

**Issue by KonradBreitsprecher** [espressomd/espresso#1848]
@davidsean @pkreissl @konradbreitsprecher

**Comment by KaiSzuttor** [comment]
we still need more components tested

**Comment by RudolfWeeber** [comment]
Can this be closed?

**Comment by KonradBreitsprecher** [comment]
test_checkpoint.py and save_checkpoint.py actually only test for a very few things. I think checkpointing this is an important feature and bugs here might be pretty silent and nasty. We should test thoroughly for parameter retrieval of ALL interaction, methods, constraints etc.

**Comment by davidsean** [comment]
I remember testing to see if I would deterministically (including the PRNG state) resume a simulation and I couldn't get it to work.

A part if it was the use of checkpoint.register as a unit test case (since in that context the variables needed to be registered as unittest objects). I see now that this is circumvented by not having  save_checkpoint.py use the unittest framework. 

Another part (IIRC) was that the last element of the seed list was not being correctly set. I'll have to check again to be sure though. Now that save_checkpoint.py is outside the UT framework it should be easier to confirm.

**Comment by RudolfWeeber** [comment]
Can this be closed?
