### ISSUE TITLE
Quaternion reference axis not documented

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1854]
The reference axis for the quaternion representation of particle orientation is not documented.

**Comment by RudolfWeeber** [comment]
On Fri, Feb 16, 2018 at 08:57:52AM +0000, Kai Szuttor wrote:
> The reference axis for the quaternion representation of particle orientation is not documented.
http://espressomd.org/html/doc/running.html#integrating-rotational-degrees-of-freedom

**Comment by hmenke** [comment]
It is a bit confusing what is the actual issue here.  I have no idea what you mean by reference axis.  Perhaps you mean axis of rotation but that is encoded in the quaternion itself.  What is indeed not documented is the *initial orientation of the particle's director* which is `(0,0,1)` by default.

**Comment by KaiSzuttor** [comment]
Okay seems, i'm confused about the quaternions...
