### ISSUE TITLE
Constant pH hangs 

### ISSUE THREAD

**Issue by helvrud** [espressomd/espresso#1981]
I tried to simulate constant pH ensemble and discovered the following

In archive the files test_one.py and test_two.py differ only in the number of added particles (line 66)
The first script hangs terminal, another runs...

Yet another issue is when I run test_three.py i get `RuntimeError: Particle node not found!
`. This script differs from test_two.py by presence of the reactions from ReactionEnsemble ( not from the constant pH ensemble, lines 78, 79 ) 

[constant_pH_test.zip](https://github.com/espressomd/espresso/files/2009828/constant_pH_test.zip)

**Comment by jonaslandsgesell** [comment]
Hey Oleg, I m on vacation. I will look into this as soon as I am back ~ 1-2 weeks.

**Comment by jonaslandsgesell** [comment]
Thanks for the report!
There was an off by 1 error in get_random_valid_p_id() in using i_random().
Therefore there was an endless loop in ConstantpHEnsemble::do_reaction()
The second problem was also related to get_random_valid_p_id() and occured when there was an invalid particle id returned. This could happen because of the reaction ensemble invalidating a particle id and the constant pH method not being aware of this. 
Both problems are fixed now.
