### ISSUE TITLE
exclusion radius in the reaction ensemble breaks detailed balance

### ISSUE THREAD

**Issue by kosovan** [espressomd/espresso#2045]
We discussed this with @jonaslandsgesell and @helvrud some time ago but apparently it was missed: if a particle is generated within the exclusion radius defined by the user, the trial configuration should be rejected, and the old configuration should be accepted. In the current implementation, new configuration is attempted up to 1000 times, until the attempt generates new particles outside the exclusion radius. In dense systems (above 0.1mol/L) this leads to incorrect sampling, and the obtained chemical potential depends on the exclusion radius.

I think the original intention was to avoid low acceptance rates which is OK as long as the physics is correct.

Possible solutions:
1. completely remove the exclusion radius - it will always lead to correct physics but maybe sometimes lower acceptance rates
2. keep the exclusion radius but then set max_tries=1 in the code and warn the user in the manual that it may break sampling if exclusion radius is not set wisely.

I am strongly in favour of solution 1. because it always leads to correct physics. Solution 2. may speed up some calculations and avoid

I could provide a fix tomorrow or tonight.

**Comment by jonaslandsgesell** [comment]
Solution 1 is not practical from my experiences too big forces may occur which leads to a broken integration step (aka an exploding system). We can rather directly reject any move which is violating the exclusion radius.
There was no original intention other than avoiding exploding systems due to too high gradients in the potential energy. As long as you have an exclusion radius compatible with your WCA interactions you make an error that is negligible.

**Comment by jonaslandsgesell** [comment]
@kosovan 
I think i fixed the problem in #2039 via commit e243340d6056b8ceecca85155cf0141fa52f39d2
There should be no more usage of max_tries or the like.
Can you also please change the title to "max*_tries in the reaction ensemble breaks detailed balance". To me the problem is not the exclusion radius itself.

**Comment by jonaslandsgesell** [comment]
We could compare our results with results from literature and see wheter they agree. e.g. https://www.sciencedirect.com/science/article/pii/S0304420302000397

**Comment by jonaslandsgesell** [comment]
This can be closed, right?

**Comment by RudolfWeeber** [comment]
What's the status?

**Comment by jonaslandsgesell** [comment]
As I said it s not the exclusion radius but the max tries (which were removed in response to this issue) which breaks statistics. Please close.
