### ISSUE TITLE
lb_cpu without EXTERNAL_FORCES silently ignores a set ext_force_density

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2078]
```python
import espressomd
import espressomd.lb

system = espressomd.System(box_l=[10.0]*3, time_step=1.0)
system.cell_system.skin = 0.01

lbf = espressomd.lb.LBFluid(                                  
		    visc=1.0,                                                           
		    dens=1.0,                                                           
		    agrid=1.0,                                                          
		    tau=1.0,                                                          
		    fric=1.0,
		    ext_force_density=[.1,.2,.3])                                    

system.thermostat.set_lb(kT=0.)
system.actors.add(lbf)
system.integrator.run(steps=100)
print system.analysis.analyze_linear_momentum(), lbf[5,5,5].velocity
system.actors.remove(lbf)
print("After removal")
print system.analysis.analyze_linear_momentum()
system.actors.add(lbf)
print("After re-adding")
print system.analysis.analyze_linear_momentum()
system.integrator.run(1)
print system.analysis.analyze_linear_momentum()
```

**Comment by fweik** [comment]
Arguably the EXTERNAL_FORCES should have no effect on the LB.
Currently this works as follows: If `!EXTERNAL_FORCES`, every LB node has a flag that indicates if the node has a force applied to it (`LBFluid_Node::has_force_density`), which is `false` initially and set to `true` if a force is applied to the node due to particle coupling or similar. If `EXTERNAL_FORCES`, every node has a force applied (the extetrnal one) and the flag is removed. The reason for this is that adding the force to the fluid has a measurable performance cost, so it is skipped where not needed.
I think the sensible solution would be to just always have the flag, and if a finite external force is set, just to set the flag on every node. Due to branch prediction I don't think this will have a relevant performance impact when the flag has the same value for all nodes. It would even give a benefit if `EXTERNAL_FORCES`, but no force is set (in this case you currently play for adding a zero-force to every node). These changes would also fix this issue.
