### ISSUE TITLE
Add test for some shapes

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2098]
* spherocylinder
  * slit pore @KonradBreitsprecher 
  * rhmoboid
  * hollow cone

**Comment by jngrad** [comment]
The Sphinx documentation currently warns against using the Rhomboid shape (@KonradBreitsprecher). I did not experience any issue when creating tests for it. The OpenGL engine had trouble rendering the rhomboid in 3D, though.

**Comment by KonradBreitsprecher** [comment]
Some shapes are rendered via brute-force rasterization with the shape's distance calculation. So if something looks odd there, it's most likely a problem in the calculation.
The warning is because the rhomboid is unprotected against wrong parameters, so for example
`corner = [1,1,1], a = [-1,0,0], b = [0,-1,0], c=[0,0,-1]` will fail. 
Basically, it fails if  `|corner| > |opposite_corner|`.  We could check for it or make it clear in the doc. Invalid shape parameters is probably an issue for some other rarely used shapes, so we should come up with a consistent solution that doesn't involve tedious work for unused features.

**Comment by jngrad** [comment]
Good point, there are currently no range checks in src/core/shapes/*.hpp to assert the validity of geometrical parameters. Without particles in the system, broken shapes (ex. missing walls in Slipore with negative radius) won't throw an exception during integration. With particles, the system throws an exception `"ERROR: Constraint violated by particle 0 dist -nan"` during integration. This should be addressed with a `throw std::invalid_argument("radius cannot be negative")` wherever necessary.
Also related to range checks: shapes attribute `double direction` can currently take any value, not just -1 and +1; is it desirable? The only application I can think of is to enable "scaling" the LJ potential without defining a new type for the constraint (i.e. `direction=+0.5` for an outward force, only half that of `system.non_bonded_inter[0, 1].lennard_jones`). If such a feature exists, it could be more intuitive if shapes had two attributes `int direction` and `double magnitude`, otherwise a range check should be used to constrain `direction` to the set {-1, +1}.
