### ISSUE TITLE
Skin should be a property of the system class and have a default value

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2125]
and not of `CellSystem`, it's not related to the cell system. It also should have a default value.

**Comment by jonaslandsgesell** [comment]
Is the skin depending on the update frequency of the verlet lists? And is the update frequency depending on the timestep, the particle masses and the temperature and maybe also external fields because all these variables influence the velocity of the particles (and therefore the distance traveled within 1/update frequency). If so, then how would one find a sensible default value without tuning the system without everything setup (and for an arbitrary unit system)?

**Comment by fweik** [comment]
If the system is simple we can make an educated guess (as Espresso does currently with LJ). If the system is complicated the user won't know the optimal skin either and has to tune anyway. If she happens to know (e.g. from previous tuning), it can just be set.
I think from an user experience perspective it is very bad that the user is confronted with an technical
detail that is unimportant to the result and has to touch the `CellSystem` which looks scary. This is
definitely a setting for advanced users that has at least intermediate knowledge about how MD works.
Also this is still confusing as the skin has nothing to to with the cell system. When I come to thing of it, it should be an argument to the integrator (as should be the time step), and not system state.

**Comment by hmenke** [comment]
:+1:  property of system

:-1:  default value (Espresso is software for an advanced MD user)

**Comment by jonaslandsgesell** [comment]
Can't we call the tune automatically e.g. on the first integration step unless the user provided manually a value for the skin thikness? That way the user does not have to set it manually.

**Comment by fweik** [comment]
We can't call tune as it modifies the system.
