### ISSUE TITLE
CMake: compiler flags should depend on compiler version

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2144]
e.g. ```WITH_COVERAGE``` adds ```fprofile-instr-generate``` which is not available for the default clang++ on ubuntu16.04

**Comment by jngrad** [comment]
To my knowledge, CMake doesn't offer a native solution to write a compatibility table. The closest feature I could find is [presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html), where one can define a different configuration for specific compiler vendors and version. In the `warnings` section, one can toggle specific compiler warnings on or off, and in the `cmakeCommandArgs` field one can add a toolchain file, which is essentially a CMake file containing the list of compiler flags as a string.

We are currently controlling the compiler-dependent flags via *interface libraries*:
```cmake
add_library(cxx_interface INTERFACE)
target_compile_options(
  cxx_interface
  INTERFACE -Wall
            -Wextra
            $<$<BOOL:${WARNINGS_ARE_ERRORS}>:-Werror>
            $<$<CXX_COMPILER_ID:Clang>:-Wextern-initializer>
            $<$<CXX_COMPILER_ID:GNU>:-Wno-clobbered>
            $<$<CXX_COMPILER_ID:Intel>:-wd592>)

if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_VERSION
                                               VERSION_GREATER "4.8.5")
  # older GCC versions don't support -Wno-pedantic which we need in src/python
  target_compile_options(cxx_interface INTERFACE -pedantic)
endif()
```

The conditional could be replaced by a generator expression, although the equivalent expression is difficult to read. Overall the current solution isn't ideal, as it requires the compiler to be compatible with GCC-style compiler flags. This is the case with the compilers we officially support (Clang, AppleClang, Intel, NVCC, HIPCC in the past), but it's not the case for MSVC. This is not an issue at the moment, because for Windows users the path of least resistance is to build ESPResSo via WSL2 (building with MSVC is complex due to the Boost dependency).

To make the current solution more maintainable, we could enforce minimal compiler versions. This would allow us to simplify these conditionals and convert several of them into short generator expressions. For example, in the conditional above we require at least GCC version 4.8.5, which isn't C++14 capable, therefore this version check always evaluates to true when CMake reaches that line when the compiler is GCC.
