### ISSUE TITLE
stress tensor should be renamed to pressure tensor

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#2200]
since it has the sign convention of a pressure tensor

**Comment by jngrad** [comment]
This can be done as part of #3718.

**Comment by fweik** [comment]
Did we agree to do this? The other possibility would be to change the sign. I think that stress is a clearer and less loaded term, it's also more correct I think, because it does not actually calculate the (thermodynamic) pressure....

**Comment by jngrad** [comment]
I've been reading a few papers this morning, and it's unclear to me what is actually calculated in the core. Cheng et Merz 1996 ([10.1021/jp952646x](https://doi.org/10.1021/jp952646x)) give the following definitions of the scalar pressure and pressure stress:

<img src="https://render.githubusercontent.com/render/math?math=P=\displaystyle\frac{1}{3V}\sum_{i=1}^{N}\left(m_iv_i^2%2b\vec{r_i}\cdot\vec{F_i}\right)" alt="P = 1/(3V) \sum_{i=1}^{N}(m_i v_i^2 + \vec{r_i} \cdot \vec{F_i})">

<img src="https://render.githubusercontent.com/render/math?math=P_{\alpha\beta}=\displaystyle\frac{1}{V}\sum_{i=1}^{N}\left(m_i(\vec{v_i})_\alpha\cdot(\vec{v_i})_\beta%2b(\vec{r_i})_\alpha \cdot (\vec{F_i})_\beta\right)" alt="P_{\alpha\beta} = 1/V \sum_{i=1}^{N}(m_i \vec{v_i}_\alpha \cdot \vec{v_i}_\beta + \vec{r_i}_\alpha \cdot \vec{F_i}_\beta)">

Subramaniyan et Sun 2008 ([10.1016/j.ijsolstr.2008.03.016](https://doi.org/10.1016/j.ijsolstr.2008.03.016)) mention that some authors drop the velocity term. In espresso, we drop the force term.

Cheng et Merz 1996 conclude that three-body and four-body bonded interactions "do not contribute to the virial or pressure, however, the contribution to the pressure tensor is in general not zero." It's unclear to me why that is, considering that their demonstration shows that the scalar pressure and pressure stress are both zero. Could it be an issue with naming conventions?

Furthermore, we have a function [`calc_bonded_three_body_stress()`](https://github.com/espressomd/espresso/blob/4e578cde72d5f383eb6a88ab20e3849f246714be/src/core/pressure_inline.hpp#L124-L150) that can only return a zero matrix, since forces from angle potentials are perpendicular to the bond distance vectors.

**Comment by fweik** [comment]
As I was saying, stress is a less loaded term with a clear (mechanical) definition. From a physics point of view, pressure is a statistical property, that can only be calculated from an ensemble, not from a configuration. I know that the term is used somewhat differently in engineering, but it is controversial, also I think there are different sign conventions, which also doesn't help.

**Comment by fweik** [comment]
Btw. I think the authoritative source for these terms is the seminal Kirkwood and Irving paper (https://doi.org/10.1063/1.1747782) from the 50s...

**Comment by jngrad** [comment]
offline discussion: is espresso the velocity term is calculated by the kinetic virial function and the force term is calculated by the particle and nonbonded virial functions.
