### ISSUE TITLE
membrane_collision is broken

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2214]
The oif membrane_collision relies on the `p.p.out_direction` being up-to-date. But the `out_direction` is updated by a bonded interaction, which are not guaranteed to be evaluated before the pair interactions are calculated.

**Comment by jngrad** [comment]
I have a similar issue with elastic membranes simulations in a fluid. In [jngrad/espresso/OIF-normals](https://github.com/jngrad/espresso/tree/OIF-normals), member `out_direction` is now updated before evaluation by `add_membrane_collision_pair_force(const Particle *p1, const Particle *p2, ...)`. The simulation does not crash during a collision anymore, however this solution isn't completely satisfactory:
* the constness of `p1` is not respected; we could consider updating the normals in `add_non_bonded_pair_forces(Particle *p1, Particle *p2, ...)` instead, using the same distance criterion to re-calculate normals only when necessary
* the case where a particle has less than 3 bonded particles (e.g. at the boundaries of an open surface) is not covered
* a membrane surface can cross itself if sufficient force is applied (this should be addressed in another function)

**Comment by fweik** [comment]
I'm currently working on a generic solution for this. If you are interested
please come talk to me next week.

**Comment by fweik** [comment]
Sorry for the delay. I'm not going to work on this. @jngrad is there anything from you? Otherwise we have to remove the feature or mark it as experimental.

**Comment by jngrad** [comment]
Haven't looked into this for a while. I'm still busy refactoring `forces_inlines.hpp` and the dihedral code. After that I'll have a better understanding of the way OIF is integrated and will look for a better solution.

**Comment by RudolfWeeber** [comment]
I took a look. My impression is that the current force calculation evaluates bonds first, so this issue probably does not arise in the 4.1 line. (src/core/algorithms/...)
However, that is not something we guarantee for the future, so the implementation of membrane collision will have to change in the next few months.


@icimrak, @fweik, @jngrad
My understanding of the current state of the discussion in Stuttgart is the following:

The problem would go away, if the membrane collision would be expressed as a force between (virtual) particles sitting at the center of the triangle faces. Then, the out direction can be calculated on the fly. This would 
* remove the dependency issue, which will probably arise quite soon due to upcoming core refactoring. Virtual sites are guaranteed to be updated before the force calculation.
* remove the OutDirection fake bonded interaction which will also interfere with upcoming core refactoring (because bonded interactions will be forbidden from changing the underlying particles, in this particular case, the out_direction property)
* this shoudl also work with open surfaces

So the new "membrane collision" would be a non-central pair force between particles sitting at the center of the respective triangles. The resulting force would be transferred (via the standard virtual sites mechanism) onto the actual particles making up the triangle.

**Comment by fweik** [comment]
> My impression is that the current force calculation evaluates bonds first, so this issue probably does not arise in the 4.1 line.

This is not correct.

**Comment by RudolfWeeber** [comment]
@fweik, I see. The fact that the single particle kernel is called ahead of the pair kernel is not sufficient, since the membrane collision interaction uses the out direction of both particles.

@icimrak, the check which should catch not-set out_direction  in membrane_collision.hpp is incorrect. It passes if only one of the two vectors is non-zero.

A failing test is in my github repo in membrane_collision_test.
The first and second force calculation on an unchanged system yield different results.
In the first force calculation, the out_direction property of either the particle 'extra1' or 'extra2' is still zero. Effectively, only the out_direction of one of the triangles is used.
In the second integration, both particles have the correct out_direction, and membrane collision uses the difference vector between them. As the triangles are not parallel to each other, the force direction in membrane_collision changes.

A minor point: The angle = acos(dot product) part can probably be skipped. You can check the dot product directly.

@icimrak, let's discuss on Skype after Jan 6th.
