### ISSUE TITLE
Bug in the implementation of the Gay-Berne potential

### ISSUE THREAD

**Issue by Kischy** [espressomd/espresso#2229]
There is a error in gb.hpp (Gay-Berne potential) that makes it impossible to use other values for \sigma_0 other than 1:

Line 83 and 84

`X = 1/(dist - Sigma + ia_params->GB_sig);`
`Xcut = 1/(ia_params->GB_cut - Sigma + ia_params->GB_sig);`

should really be

`X = ia_params->GB_sig / (dist - Sigma + ia_params->GB_sig);`
`Xcut = ia_params->GB_sig / (ia_params->GB_cut - Sigma + ia_params->GB_sig);`

according to the manual [(http://espressomd.org/html/doc4.0/inter_non-bonded.html#gay-berne-interaction)](http://espressomd.org/html/doc4.0/inter_non-bonded.html#gay-berne-interaction) (see the second equation).

**This error also occurs in lines 196 and 197**.

**Comment by RudolfWeeber** [comment]
Thanks for reporting this. Pull request #2424 applies these corrections.
We now also test a Python version of the expression in the user's guide against the code.

Since there is no test for the forces/torques (we did not find analytical expressions) the PR downgrades Gay-Berne to an experimental feature.
You need
#define EXPERIMENTAL_FEATURES
in myconfig.hpp to use it.
