### ISSUE TITLE
What does python_dp3m_adaptive_tune(self) method? 

### ISSUE THREAD

**Issue by vanadiuz** [espressomd/espresso#2291]
Dear developers, 
the documentation does not say how this method works. 💁‍♂️ Could you please tell me which method to use if I want to REtuning P3M every N integration steps? 🤓
Thanks in advance!

**Comment by hmenke** [comment]
If you have to re-tune, I guess you could use the private `_tune()` function (which is common to all electrostatics methods).  Otherwise you pass the `"tune"` argument on construction.

Here are the relevant functions for `P3M`:
https://github.com/espressomd/espresso/blob/c1d850ef3c4bee39f164acc6077cde547f0e2014/src/python/espressomd/electrostatics.pyx#L255-L269

**Comment by RudolfWeeber** [comment]
I'm not sure, whether  #1937 is fixed. The following works in spite of
that issue.
p3m=DipolarP3M(prefactor=1,accuracy=1E-3,tune=True)
s.actors.add(p3m)
s.integrator.run(1000)
print "Retuning"
s.actors.remove(p3m)
p3m=DipolarP3M(prefactor=1,cao=0,mesh=0,r_cut=0,accuracy=1E-4,tune=True)
s.actors.add(p3m)

**Comment by vanadiuz** [comment]
@RudolfWeeber , I thought so 😄, thanks!

**Comment by fweik** [comment]
I take this as resolved. Still #1937 should probably be fixed.
