### ISSUE TITLE
Does IMMERSED_BOUNDARY actually require VIRTUAL_SITES?

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2327]

**Comment by RudolfWeeber** [comment]
IMMERSED_BOUNDARY contains the volume conservation and surface stiffness stuff. It is not clear, if there is a remaining link with the VIRTUAL_SITES_INERTIALESS_TRACERS

**Comment by fweik** [comment]
I think the feature is not required at all. As far as I can tell that guards only bonded interactions and the volume forces that do not have a performance impact if not enabled. Also I think it is misleading, because some of this features might be useful in totally different contexts. This is the wrong level of abstraction for Espresso. Espresso should have methods that can be combined to build an immersed boundary model (say, of a red blood cell), and not a monolithic features that comprises multiple methods that could be used separately.

**Comment by RudolfWeeber** [comment]
On Tue, Apr 09, 2019 at 06:43:16PM +0000, Florian Weik wrote:
> I think the feature is not required at all. As far as I can tell that guards only bonded interactions and the volume forces that do not have a performance impact if not enabled.
So, for 4.1, we take those out and remove the myconfig-feature
IMMERSED_BOUNDARIES. We also move the source files for the bonded IAs.

> Also I think it is misleading, because some of this features might be useful in totally different contexts. This is the wrong level of abstraction for Espresso. Espresso should have methods that can be combined to build an immersed boundary model (say, of a red blood cell), and not a monolithic features that comprises multiple methods that could be used separately.
I agree with this assessment, but would not milestone any work with
that regard for 4.1 without a discussion in the Espresso meeting.

**Comment by RudolfWeeber** [comment]
Part of 2807
