### ISSUE TITLE
 dawaanr-and-dds-gpu hangs in CI on AMD GPU

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2472]
or are very slow. This looks like technical issue. (cf. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/68418 e.g., where the test took more than 2500 sec). The problem did not go away when executing only one job at a time (see #2471).

**Comment by mkuron** [comment]
Outside of the CI, this test works just fine and completes in 1.5 seconds.

**Comment by mkuron** [comment]
Outside of the CI, this test works just fine and completes in 1.5 seconds. Even inside the Docker container! It must be something about parallel testing. The issue was introduced only recently, perhaps by #2462. Are multiple tests being run simultaneously, @fweik? https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/68418 sure looks like it -- the added up test durations are greater than the job timeout.

**Comment by fweik** [comment]
I checked in the meantime with running the gpu tests serially, that did not really help. I'll recheck tomorrow, I agree that this has to be some sort of scheduling problem.

**Comment by mkuron** [comment]
I tried `ctest -j2 -L gpu` to get the tests to run parallel, but as far as I can tell, the tests aren't even running in parallel. There definitely are a few things odd here.
By the way, while I was doing these tests, Gitlab was running its own tests on my computer. So while I can see that the tests are slowed down by overcommitting the GPU, a moderate level of overcommitment seems fine.

**Comment by fweik** [comment]
I changed the cmake today so that gpu jobs don't run in parallel because I thought this was the problem, but apparently not.
