### ISSUE TITLE
CI failures due to coverage collection

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2521]
We need a solution for the `lcov`-related issues like here: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/75623
No idea what the cause of this is. Rerunning usually fixes the issue, but not always.

**Comment by fweik** [comment]
The problem persists: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/76701, there is now a failure in almost every pipeline.

**Comment by jngrad** [comment]
Difficult to say since the container exits on failure before the artifacts get uploaded, so we cannot browse the files. Tinkering with lcov locally suggests the error message is raised when the gcno file is missing:

| gcda    | gcno           | stderr |
| :---: | :---: | :--- |
| present | present        |        |
| present | missing        | `geninfo: ERROR: $path/Variant_test.cpp.gcno: could not open file` |
| present | empty          | `geninfo: WARNING: empty $path/Variant_test.cpp.gcno (skipped)` |
| present | corrupt head | `geninfo: ERROR: $path/Variant_test.cpp.gcno: found unrecognized gcno file magic` |
| present | corrupt tail | `geninfo: ERROR: $path/Variant_test.cpp.gcno: reached unexpected end of file` |
| missing | present        |        |
| empty   | present        | `$path/Variant_test.cpp.gcda:cannot open data file, assuming not executed` |

We could open a PR with a modified `/maintainer/CI/build_cmake.sh` that prints the list of gcno files at multiple stages, wait for the first container to fail, then inspect the log file to see at which stage in the script the gcno files get erased. It might also be the compiler failed to generate the gcno files.

**Comment by fweik** [comment]
I *think* the runners can be run locally for debugging.

**Comment by mkuron** [comment]
While a job is running, you can even click the "Debug" button on its GitLab page and get a terminal in your browser. Just add a `sleep 10000` to the end of the build script first so the terminal session doesn't get killed when the build finishes.

**Comment by fweik** [comment]
This is still a problem (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/76169)

**Comment by fweik** [comment]
If fixed, #2533 has to be reverted.

**Comment by KaiSzuttor** [comment]
May it be that there is interaction with ccache?
