### ISSUE TITLE
LB: lattice_switch is ambiguous

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#2556]
The global variable `lattice_switch` is currently defined as:
https://github.com/espressomd/espresso/blob/0682e84736bd6d8b0131078a0551d35dd1a920c6/src/core/grid_based_algorithms/lattice.hpp#L34-L43

And it is used like this:
https://github.com/espressomd/espresso/blob/0682e84736bd6d8b0131078a0551d35dd1a920c6/src/core/grid_based_algorithms/lb_particle_coupling.cpp#L48-L59

A few issues here:
* the numerical values are not connected to the variable, causing documentation decay (the Doxygen blocks are already outdated)
* the `#ifdef` statements seem redundant with the global variable; shouldn't writing `lattice_switch = LATTICE_LB_GPU` when LB_GPU isn't compiled in raise an exception?
* is the statement `lattice_switch = LATTICE_LB & LATTICE_LB_GPU` legal (documentation says yes) and if so, in a switch, when should LB CPU evaluation happen before LB GPU evaluation?

**Comment by KaiSzuttor** [comment]
* you are right about the fact that this whole concept is not best practice in C++, it's a relict of the old C code.
* the ```#ifdef```s are not redundant, since you don't want to check if the feature is not even compiled in
* ```lattice_switch = LATTICE_LB & LATTICE_LB_GPU``` should not be legal at all

I think the way to go would be to have a global ```enum class ActiveLB { NONE, CPU_LB, GPU_LB }```
In the best of all worlds you would hide that within the non-existing LB class and have an interface that tells which LB is currently active.

**Comment by jngrad** [comment]
Sorry, I meant to write `lattice_switch = LATTICE_LB | LATTICE_LB_GPU` with a pipe instead of the ampersand! Just found the function in the LB interface that throws an exception when an illegal value is used. And the `#ifdef` only prevents exposing calls to functions not compiled in.

Using an enum solves the ambiguity and allows writing conditional statements with `==` instead of the ampersand. If you're ok with that change, I can take care of it after the 3pt coupling PR is merged.
