### ISSUE TITLE
analyze p_isnt has neither docs nor testcase

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#259]

**Comment by jngrad** [comment]
There was some p_inst analysis feature removed in 4.0:
https://github.com/espressomd/espresso/blob/7981af6e58bdcb6e4bbe6ebdd310b9b47b14b123/NEWS#L280-L287
However `git log -S "p_inst"` could not return any analysis tool with that name. Even when tcl functionality was removed in #933, p_inst was nothing more than a variable in a pressure analysis function. The string `analyze p_inst` still appears today in comment lines, but p_inst is just a global variable that gets updated in the integration loop and is covered by tests.

@RudolfWeeber @fweik If this issue is still relevant now, could you please indicate where this function is located? Otherwise, the issue can be closed.

**Comment by RudolfWeeber** [comment]
The analysis routine it self is probably gone, but the underlying code probably is still around.

See #2544
