### ISSUE TITLE
Coding Style/Review Guide

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2601]
We should somewhere specify what use of C++ is acceptable and make a check list for code reviews. 
Generally I would not write a complete coding style but would refer to
something like the [Core Guidline](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) and add some specific rules for our project, like our [Naming Convention](https://github.com/espressomd/espresso/wiki/Naming-conventions-and-folder-structure).

Other ideas for rules are:
- No use of `malloc`/`free`
- No use of `const_cast`, except when interfacing with C libraries
- `east const`
- Everything that can be `const` should be
- No bare owning pointers
- No bare loops
- No macros
- ...

some of these can be automatically checked, and should be if it is
possible to limit e.g. `clang-tidy` only to PRs (or if all the legacy code
is cleaned up).

I think there are multiple benefits of codified rules, e.g. quicker code
review because authors can check her PR before it is opened and
reducing the potential for bikeshedding. Also many of our contributors
are not C++ experts for whom any guidance through the complexities
of the language would be helpful.

**Comment by KaiSzuttor** [comment]
* no C-style casts
 * no wildcard imports in cython/python

**Comment by fweik** [comment]
For things that can be checked by `clang-tidy` we should keep track of the corresponding rules...

**Comment by fweik** [comment]
Potential spec for physical code organization: https://github.com/vector-of-bool/pitchfork

**Comment by fweik** [comment]
Style for python doc strings: https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by jngrad** [comment]
> We should somewhere specify what use of C++ is acceptable and make a check list for code reviews.

done in [wiki/Code review#Style guide](https://github.com/espressomd/espresso/wiki/Code-review#Style_guide)

> Potential spec for physical code organization: https://github.com/vector-of-bool/pitchfork

done in [wiki/Software design#Internal libraries](https://github.com/espressomd/espresso/wiki/Software-design#Internal_libraries)

> Style for python doc strings: https://numpydoc.readthedocs.io/en/latest/format.html

done in [wiki/Documentation#sphinx](https://github.com/espressomd/espresso/wiki/Documentation#sphinx)

**Comment by KaiSzuttor** [comment]
> done in wiki/Software design#Internal libraries

IIRC, @RudolfWeeber did not agree to use this structure (although it is used already)

**Comment by jngrad** [comment]
> > done in wiki/Software design#Internal libraries
> 
> IIRC, @RudolfWeeber did not agree to use this structure (although it is used already)

I wrote "typically adopt the Pitchfork layout" to reflect that. I've now reformulated that section to make it clearer we do not enforce it. If we one day decide to enforce a layout XYZ, we will update page [Naming conventions and folder structure](https://github.com/espressomd/espresso/wiki/Naming-conventions-and-folder-structure) accordingly.

In the context of the [Software design](https://github.com/espressomd/espresso/wiki/Software-design) page, I find the Pitchfork layout more intuitive to explain the "pointer to implementation" idiom and the "separation of concerns" design. For espresso I don't have a strong opinion; the main advantage of the Pitchfork layout over the espresso layout is that with Pitchfork, we don't have to trust contributors to not accidentally include the implementation header files because CMake will prevent it.
