### ISSUE TITLE
LB thermostat cannot be checkpointed

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2652]
```set_lb``` requires a LBFluid instance which is not present at the time the state for the thermostat is set

**Comment by RudolfWeeber** [comment]
LB itself has checkpointing via system.actors.
Both, the Actors container and the Actor base class have __getstate__ and __setstate__ methods.
The condition for this to work is that the individual actors restore all their state in the core via the _set_state_in_es_core() method based on the self._params struct.

The actual flow field is not checkpointed, but LBFluid has methods for saving and loding it to/from a file.
this could be triggered in the checkpointing, but probably not via LBFluid.__setstate__, because the checkpoint directory is not known there.

The second issue is that the thermostat needs a reference to the active LB fluid.
It is not possible to checkpoint the LB class via the thermostat's checkpointing, because then two versions would be restored, one via system.actors and one via the thermostat.
A not so nice workaround is to make sure that actors are restored before thermostat and provide a method in System which returns a reference to the currently active LB fluid.
