### ISSUE TITLE
implement being able to change LB temperature without affecting RNG state

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2682]

**Comment by fweik** [comment]
#2666 solves this for Langevin. I think for the other it can be done in the same way.
The deeper issue here is that the state of those thermostats has static lifetime, so they already exist on program start, because of this the (logical) class invariant `has seed` can not be maintained by simply only defining a constructor that needs a seed. Eventually this has to addressed on this level.

(This is my understanding from an offline discussion from yesterday)

**Comment by RudolfWeeber** [comment]
@kaiszuttor, do you want to address this or should we de-milestone?
