### ISSUE TITLE
No such container error at then end of CI job

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2742]
See https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/101379,
at the end the jobs fails with
```
ERROR: Job failed (system failure): Error response from daemon: No such container: 1cfc32f626eb39990824142f4eb00450bca2426532342c880f987140fece7f28 (executor_docker.go:932:1s)
```

**Comment by mkuron** [comment]
That problem is known to occasionally occur in Gitlab Runner, see e.g. https://gitlab.com/gitlab-org/gitlab-runner/issues/3698, https://gitlab.com/gitlab-org/gitlab-ce/issues/43286, https://gitlab.com/gitlab-org/gitlab-runner/issues/3395, https://gitlab.com/gitlab-com/support-forum/issues/3864. These kinds of errors are simply out of our control, which makes it completely unrealistic to get 100% CI success rate.
