### ISSUE TITLE
Sphinx autodoc should include __init__ constructor for bonded interactions

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#2780]
Bonded interactions are set up using an `__init__` constructor. It is therefore absolutely fine that in-code documentation documents the parameters there, see as an example from `src/python/espressomd/interactions.pyx`:
```
[...]

class HarmonicBond(BondedInteraction):

     def __init__(self, *args, **kwargs):
         """
         HarmonicBond initializer. Used to instantiate a HarmonicBond identifier
         with a given set of parameters.
 
         Parameters
         ----------
         k : :obj:`float`
             Specifies the magnitude of the bond interaction.
         r_0 : :obj:`float`
               Specifies the equilibrium length of the bond.
         r_cut : :obj:`float`, optional
                 Specifies maximum distance beyond which the bond is considered
                 broken.
 
         """
         super(HarmonicBond, self).__init__(*args, **kwargs)

[...]
```
By default `:special-members:` like `__init__` are ignored by autodoc and in general, I think, we want to keep it that way.
However, as is now, the online documentation of the bonded interaction in the [`espressomd.interactions` module](http://espressomd.org/html/doc/espressomd.html#module-espressomd.interactions) is pretty pointless, as it doesn't tell you which parameters are expected/available when setting up a bonded interaction.
This issue has been brought to attention by a new user of ESPresSo.

**Comment by jngrad** [comment]
Private class members (one leading underscore in the name) and special members (two leading underscores) aren't meant to be used directly by the user, so it is not immediately obvious why they should appear in the documentation. With the way Sphinx represents classes,
```
 class espressomd.interactions.HarmonicBond(*args, **kwargs)
    Bases: espressomd.interactions.BondedInteraction
```
it feels natural to put the constructor parameters directly in the class docstring, rather than in the constructor docstring. However [PEP 257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring) specifically allows docstrings in special members like `__init__()` and the [Napoleon samples](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) shows both options: arguments in constructor in `ExampleClass` vs. arguments in class in `ExampleError` (see [section Classes](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#384-classes) in the Google Python Style Guide).

So this is more like a style preference. Since most constructors have no docstring or an automatically generated one, I propose we only display `__init__()` methods when they have a docstring.

**Comment by KaiSzuttor** [comment]
We once decided to follow the [numpy style](https://numpydoc.readthedocs.io/en/latest/format.html) for documenting python. The style guide for numpy says that the constructor should be documented in the class docstring. We should be following one guideline and be consistent. Therefore, I think it would be cleaner to move the existing documentations of ```__init__``` functions to the respective class docstring.

**Comment by KaiSzuttor** [comment]
Also this is not much work, affected classes are:

- [ ] ```Diamond```, diamond.pyx
- [ ] ```Stream```,  MDA_ESP/__init__.py
- [ ] ```NonBondedInteractionHandle``` in interactions.pyx
- [ ] ```BondedInteraction``` in interactions.pyx
- [ ] ```FeneBond``` in interactions.pyx
- [ ] ```HarmonicBond``` in interactions.pyx
- [ ] ```BondedCoulomb``` in interactions.pyx
- [ ] ```BondedCoulombSRBond``` in interactions.pyx
- [ ] ```ThermalizedBond``` in interactions.pyx
- [ ] ```HarmonicDumbbellBond``` in interactions.pyx
- [ ] ```RigidBond``` in interactions.pyx
- [ ] ```Tabulated``` in interactions.pyx
- [ ] ```Virtual``` in interactions.pyx
- [ ] ```IBM_Triel``` in interactions.pyx
- [ ] ```IBM_Tribend``` in interactions.pyx
- [ ] ```IBM_VolCons``` in interactions.pyx
- [ ] ```QuarticBond``` in interactions.pyx
- [ ] ```CollisionDetection``` in collision_detection.pyx```
- [ ] ```P3M``` in electrostatics.pyx
- [ ] ```P3MGPU``` in electrostatics.pyx
