### ISSUE TITLE
Utils function not compatible with required boost version

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2837]
```Utils::make_lin_space``` does not build with boost version 1.53 which is currently the version we require. By inspection of the boost repo, I suppose we need at least 1.57 (from this version on at least the namespaces exist).

**Comment by KaiSzuttor** [comment]
see #2839

**Comment by fweik** [comment]
For orientation: boost 1.53 was released on February 4th, 2013.

**Comment by mkuron** [comment]
Sure, but we really don't want to have people recompile Boost just because their HPC system's version is too old. As far as I can tell, only `boost::iterators::make_counting_iterator` and `boost::iterators::make_transform_iterator` are affected. Looking at https://github.com/boostorg/iterator/blob/boost-1.53.0/include/boost/iterator/counting_iterator.hpp, all you need to do is replace `boost::iterators::` with `boost::`...

**Comment by KaiSzuttor** [comment]
I've already tried that and it did not work out

**Comment by fweik** [comment]
All we need to do is add more unmaintainable workarounds...

**Comment by mkuron** [comment]
How is this an unmaintainable workaround? To this date, it's still part of the official Boost API.

**Comment by fweik** [comment]
Ah sorry, I did't see that this also working in newer boost versions...

**Comment by KaiSzuttor** [comment]
I don't really see the point in
> we really don't want to have people recompile Boost just because their HPC system's version is too old

that's not a big issue and on a HPC system you normally have support, so you don't even have to do it yourself

**Comment by fweik** [comment]
@KaiSzuttor did you check what the minimal version is that is required?

**Comment by KaiSzuttor** [comment]
I'm currently checking...

**Comment by fweik** [comment]
If you find out, it has to be changed in cmake, and we have to make sure that we have a container with this version.

**Comment by KaiSzuttor** [comment]
1.55 would work
