### ISSUE TITLE
Mark checkpointing as experimental and add more tests

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2896]

**Comment by RudolfWeeber** [comment]
The docs now clearly state the limitations and limited testability.
I'm de-milestoning this, but we should add an end-to-end test with a reasonably complex simulation setup in the long run.

**Comment by KaiSzuttor** [comment]
@RudolfWeeber have you checked the coverage of the checkpointing tests?

**Comment by RudolfWeeber** [comment]
On Tue, Aug 06, 2019 at 01:06:44AM -0700, Kai Szuttor wrote:
> @RudolfWeeber have you checked the coverage of the checkpointing tests?
Up to a point, yes. It includes the main integrator features, standard script interface classes, ScriptObjectRegistry-derived script interface classes such as LBBoundaries and Constraints.
Also @pkreissl and me have run end-to-end tests on our current research projects.

**Comment by jngrad** [comment]
Tests were added for constraints (#3105), thermostats and integrators (#3245) checkpointing in 4.1.1.

**Comment by jngrad** [comment]
Progress report:
- checkpointing testing has improved considerably since 4.1.1
- multiple combinations of features are tested to detect interactions (e.g. due to the order in which global variables are reloaded)
- accidental double checkpointing of global variables has been sorted out (#4276)
- non-checkpointable features raise an exception when checkpointed (#4287)
