### ISSUE TITLE
Outdated cuda version picked when using clang as compiler

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#2994]
At ICP, there is a Cuda 8 installation in /usr/local/cuda-8.0
I'm using clang++ as NVCC host compiler and
cmake -DWITH_C?UDA=on
Since Espresso requires Cuda 9, the installation in/usr/local/cuda-8.0 should be disregarded.

More generally, the cuda detection code in CMakeList.txt is somewhat involved. 
If possible, that should be simplified.

**Comment by mkuron** [comment]
Clang 6.0 does not pick up CUDA 9.0 because it only supports CUDA 7.0-8.0 (Clang 7.0 is the oldest version that picks up CUDA 9.0). Clang only uses the NVPTX assembler from the CUDA package, and there version 8.0 (or even older ones) are sufficient for Espresso. CUDA 9.0 is the oldest version with an nvcc that supports C++14, but Clang has supported C++14 in device-side code since around Clang 4.0 and CUDA 7.5.

So this is not actually a problem.

**Comment by fweik** [comment]
This is not an issue, with clang you have to use the CUDA that clang proposes, which is what we do.
As for the cmake code: I can't see how this can be improved structurally, it has one level of abstraction
which is needed because we decided we want to proided CUDA support in multiple ways.
