### ISSUE TITLE
Remove debug macros

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3095]
Remove the debug macros from `debug.hpp` and the corresponding includes. They are less powerful than a debugger and add a lot of noise and coupling.

**Comment by fweik** [comment]
This can probably be automated with a clever combination  of `unifdef` and `grep`.

**Comment by jngrad** [comment]
<s>Please cherry-pick  0c63f76 first! One debug macro is misnamed and can fool tooling.</s> Update: dealt with in #3098. Use grep on [maintainer/configs](https://github.com/espressomd/espresso/tree/python/maintainer/configs), too, and update [doc/sphinx/installation.rst](https://github.com/espressomd/espresso/blob/python/doc/sphinx/installation.rst) accordingly.

**Comment by RudolfWeeber** [comment]
Once the debug macros are gone, we can also remove the nocheck_maxset CI job.

**Comment by jngrad** [comment]
Obvious candidates were removed in #3098. The 12 remaining ones are located in parts of the core I'm less familiar with. These grep commands print the number of occurrences of debug/trace macros:
```bash
for f in `grep -Phor '[A-Z_]+_DEBUG' src maintainer doc testsuite | sort | uniq`; do echo $f; grep -r $f src maintainer doc testsuite | wc -l; done
for f in `grep -Phor '[A-Z_]+_TRACE' src maintainer doc testsuite | sort | uniq`; do echo $f; grep -r $f src maintainer doc testsuite | wc -l; done
```

**Comment by jngrad** [comment]
Some debug messages could be converted to comments. I've seen a few helpful `CELL_TRACE` printf messages that clarified what the code was doing when moving particles to neighboring cells.

**Comment by jngrad** [comment]
The `debug.hpp` include is required in some places to get access to the global variable `this_node`. It's not always possible to use `communication.hpp` because we cannot include `mpi.h` in CUDA code, e.g. in `EspressoSystemInterface.hpp`.

There is a global variable `regular_exit` that doesn't seem used. The `CUDA_DEBUG` guards a call to `cudaDeviceSynchronize()`, if it's helpful for debugging GPU code please let me know, otherwise I'll remove it in the final PR.

**Comment by fweik** [comment]
Using `this_node` but not needing access to a communicator sounds odd.
