### ISSUE TITLE
Convert active matter and reaction ensemble tutorials to ipython

### ISSUE THREAD

**Issue by mkuron** [espressomd/espresso#3249]
The students last week struggled quite a bit with the active matter tutorial because it was the only one not in ipython yet.

**Comment by jonaslandsgesell** [comment]
I suggest to delete the old reaction ensemble tutorial completely.

**Comment by KaiSzuttor** [comment]
>I suggest to delete the old reaction ensemble tutorial completely.

i think thats the wrong issue

**Comment by jngrad** [comment]
Tutorial reaction ensemble: replaced by the constant pH tutorial in 4.2.

Tutorial active matter: the LaTeX file was converted to Jupyter in [jngrad/espresso/fix-3249](https://github.com/espressomd/espresso/compare/python...jngrad:fix-3249).
```sh
# to get a readable diff
git show 9fd068464b:doc/tutorials/06-active_matter/06-active_matter.tex | sed -r 's/^(.*)$/    "\1\\n",/' > 06-active_matter.tex.bak
git show 961ba8e776:doc/tutorials/06-active_matter/06-active_matter.ipynb > 06-active_matter.ipynb.bak
meld 06-active_matter.tex.bak 06-active_matter.ipynb.bak
```
Everything related to LaTeX or BibTeX was also removed.

@mkuron: how should we proceed with the exercises and solutions?
1. @KaiSzuttor once looked into Jupyter notebooks with an add-on to mask solutions, but I don't remember if he found a solution that would be compatible with our CI pipeline. 
2. Alternatively, we could remove the exercises and convert each solution into a Jupyter notebook. This means editing `06-active_matter.ipynb` to move some paragraphs to the relevant `part1-enhanced_diffusion.ipynb`, `part2-rectification_geometry.ipynb`, `part3-rectification_simulation.ipynb`, and `part4-flow_field.ipynb` notebooks.

**Comment by jngrad** [comment]
Here is a solution to mask solutions and prevent them from running when clicking on "Run all cells":
* install the NB extensions, and push the javascript and CSS of the "exercise2" plugin into your local jupyter installation:
  ```bash
  # install nbcontribs
  pip3 install --user jupyter_contrib_nbextensions
  # copy javascript and css
  jupyter contrib nbextension install --user
  # enable exercise and its dependencies
  jupyter nbextension enable rubberband/main
  jupyter nbextension enable exercise2/main
  ```
  Please note this will bring in or update a lot of dependencies. Among those, the `tornado` dependency, if too recent, can create compatibility issues with old versions of Jupyter.
* start ipypresso, open a tutorial, find a cell containing a solution, convert it to Markdown and add strings ```` ```python```` before the first line and ```` ``` ```` after the last line to pygmentize the code. Insert an empty code cell below. Use Shift+left-click to drag a red box around the markdown cell containing the question and the markdown cell containing the code solution to highlight them both, then click on the "exercise2" button to hide the solution.

In CI, we need to convert those markdown cells back into code and delete the next code cell (which should be empty).

There are a few glitches if you forget to convert the code cell into a markdown cell before clicking the "exercise2" button (I saw unicode glyphs being inserted, probably as a workaround for a known bug with matplolib).

@biermanncarl is currently looking into this.

Since the original issue here was converting the tutorials into IPython, and this task has been completed, I'm closing this. Feel free to open tickets to any tutorial(s) that you would like to see improved with this `exercise2` Jupyter add-on.
