### ISSUE TITLE
Requirements for bond breakage

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3294]
This is the outcome of a discussion during the offline Espresso meeting.
Potential users of this feature, please comment on this issue, explaining what you agree to and what should be added/changed/removed.
Once the requirements are clear, I'll try to write a plan for implementation.

The feature should provide the ability to remove bonds between particles, once a certain criterion is met.
* all pair bonds in the system should be considered in every time step
* the decision criterion can depend on:
  * bond length or bond energy or bond force (they are exchangeable for conservative bonds)
  * and/or a probability (evaluated via a randdom number)
* Likely, a two step process is needed, where first all breakages are queued and only after that all system modifications are performed. (analogous to collision detection)
* Some mechanism to safely interupt the integration is needed to do model-dependent custom stuff. The runtime error queue present in Espresso could be used
* after removing the bond, which further changes to the system need to be supported in the core (and thus, in parallel). Depending on what's needed, these actions have a high complexity and require a particle resort and verlet lsit invalidation anyway. 
  * chaning particle types of affected particles?
  * removing bonds between base particles of virtual sites? (i.e., undo the bind_at_point_of_collision scheme of the collision detectoin)

Questions:
  * Is it necessary to make the criterion paricle type specific?
  * If yes, do we need to support several criteria for a given bond type (for various combintaions of particle types)
  * Do we need a criterion in which the breakage probability depends on the energy? If so, what functional form might make sense?

**Comment by itischler** [comment]
I would say, that this does not need to be particle type specific, however in my case I would need a bond type specific criteria, because only bonds that are part of the reaction should be able to break.
The criteria (bond length, energy, force and probability) are sufficient enough (for my cases I will take the probability criteria).
The runtime errors should contain the contain the the particles, between which the bond was broken, however I am not sure if more information (like which criteria was met, or properties like energy at the time of breaking) could be helpful to be contained in that error.

**Comment by christophlohrmann** [comment]
- I would like to see the option to make it type-specific so that only a few bonds can break and others can't
- For the criteria I think one criterion per bond type would be enough. The variation can be done by choosing the particle type combination
- breakage based on force, not energy is enough for me.
- especially when breaking is based just on a fixed probability, checking once every N time steps should be sufficient

**Comment by kosovan** [comment]
@RudolfWeeber is this bond-breaking algorithm intended to represent a specific mechanism of bond breaking, or is this the "kinetic" alternative to modeling chemical reactions that we discussed at the Espresso school?

We might want to use this feature too, for modeling chemical reactions where bonds are created between polymers.

Should the criterion be implemented in the Espreso core, or specified as the script level, specific to each problem?

I think that it would be desired to specify what thermodynamics (what ensemble) this feature should represent. Then one can come up with an analytical solution for simple systems, that can be used as a test case to verify that the implementation is correct.

**Comment by bindgens1** [comment]
@RudolfWeeber 
Sorry for the delayed reply!

A bond specific breakage criterion would be sufficient for me. I have so far only one type of colloids in my system. Later on several different colloids might be added but this is not necessary for now. Since multiple e.g.: Harmonic or tabulated bonds are supported I can get around with this as long as each bond has it's own breakage criteria. 

As for the rest: I might include a hysteresis in the force separation tables to mimic approaching and receding spheres (this changes the contact angle in in-vitro systems and thus the breakage behaviour). I'm not sure if there are other customers for such a system besides me.

**Comment by jngrad** [comment]
Feature implemented in #4456. Closing.
