### ISSUE TITLE
Uncaught exception in System.number_of_particles()

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3495]
An uncaught exception in `espressomd.system.System.number_of_particles()` leads to a cryptic error message without segfault:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "system.pyx", line 447, in espressomd.system.System.number_of_particles
IndexError: _Map_base::at
```
The `IndexError` is actually an `std::out_of_range` in the core.

**Comment by fweik** [comment]
That is actually a core/cython problem, probably just forwarding the `out_of_range` exception would be more meaningful. (Assuming the exception is cause by a non-existent type)

**Comment by jngrad** [comment]
My solution: I'm now throwing if the type isn't part of the map object, and catch with `handle_errors`.

**Comment by jonaslandsgesell** [comment]
@jngrad that is a functional solution. The code throws because (probably) the type does not exist in the map. 

The types for which the map tracks the number of particles (when using the normal functions for adding or removing particles from the system) need to be registered first. Only then one can access the number of particles for the given type.

We decided to not automatically registering every type (when adding a particle) such that no unneeded memory is used in the case of enormous numbers of types.

In contrast to looping over all particles and counting the numbers of particles this approach saves time (because only changes to particles are registered). This is useful for example in the reaction ensemble, where the number of particles needs to be known in every Monte Carlo step.

**Comment by fweik** [comment]
I would in principle be possible to build the index on demand, which I think would be preferable, maybe I'll fix this quickly. Your fix is for sure better than the uncaught exception.

**Comment by fweik** [comment]
Ok it's broken anyway, because it does not track programmatic particle or type changes.

**Comment by jonaslandsgesell** [comment]
The counting mechanism is aware of any changes in particle number occuring due to a call to set_particle_type() or remove_particle() in particle_data.cpp
(through invoking remove_id_from_map() or add_id_to_type_map() ). These are the "normal functions for adding or removing particles from the system" I meant above.

Not sure how much effort would need to be placed into making this aware of possible other places (across nodes?) where particles may be changed/deleted.

**Comment by fweik** [comment]
There is other systems that can add/remove particles and change types e.g. by collisions. I don't think it's feasible to track those state changes on the head node, but we can do the same thing as with the node index, e.g. drop it on change and rebuild it on demand. In principle this should be build into the RE, but I can't even really figure out where the entry points are :-)

**Comment by jonaslandsgesell** [comment]
The reaction_algortihms implemented in reaction_ensemble.hpp all use set_particle_type() or remove_particle() from particle_data.hpp to change particle numbers (i.e. on the head node). The number of particles is then retrieved by calling number_of_particles_with_type() from particle_data.hpp.

The Monte Carlo moves for the reaction algorithm are then performed on demand by calling the corresponding functions from the python level. This cannot be automated further because the number of MC steps needed strongly depends on the system. 

You can for example step through the reaction ensemble example in the samples folder to explore this call hirachy :)
