### ISSUE TITLE
Walberla: Sort out checkpointing and related tests

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3513]
This likely depends partially on thermalization and the LB thermostat working with Walberla.

The corresponding tests are diabled at CMake level.

**Comment by RudolfWeeber** [comment]
@jgrad, did I understand correctly that you fully restored checkpointing for Walberla?

**Comment by jngrad** [comment]
The checkpointing was restored for everything except LB and EK. I still haven't looked into serializing the LB fluid.

**Comment by RudolfWeeber** [comment]
Ah right. We still need a populations setter/getter. The original version by @itischler was incompatible with the switchable lattice model, because now the stencil size is no longer fixed. Also, we gave up on the exact mapping between ES 4.1 and Walberla stencil index order.

 

In addition to the populations, the last applied force has to be checkpointed, since it enters into the lb fluid velocity calculation.

 

If all goes well, the actor parameters themselves should be handled by Python.

 

Setting/getting the lb fluid RNG counter is also not yet implemented. (The counter is hanlded by the thermalized versions of LbWalberlaBase, not by Esprseso as for the old LB)

**Comment by jngrad** [comment]
Can waLBerla serialize its state? A checkpointing mechanism was implemented in Kohl et al. 2018 ([10.1177/1094342018767736](https://doi.org/10.1177/1094342018767736)).

**Comment by jngrad** [comment]
The LB populations and last applied forces are now checkpointed (2f9e8b34bb). The EK checkpointing is still commented out.

**Comment by jngrad** [comment]
I quickly experimented with a boost solution to serialize the LB blockforest (5196f7fd69). This is a more compact solution than the one we currently have, and is probably more efficient since we only have one MPI call per checkpointing instead of two MPI calls per LB node. It also removes the boolean flag to defer ghost communication, and keeps the serialization logic inside the walberla class. It's more convenient once we start supporting both single- and double-precision, because our current checkpointing infrastructure casts float to double when saving, and double to float when loading, which could introduce precision loss.

It has several drawbacks, though:
- there is currently a single block in the blockforest per MPI rank, but if we have multiple blocks, will the `m_blocks` iterator traverse the underlying `std::map` in the same order when reloading the checkpoint? To reload the blocks in the correct order we could store the block id, but `block_it->getId()` throws a compiler error about an unimplemented virtual method.
* is `boost::serialization` backward compatible, i.e. can we load a checkpoint file written by an ESPResSo binary compiled with different boost versions? The boost version number is stored, and there was a break in compatibility in boost 1.42.
* serialization will preserve the structure of the domain decomposition, which would prevent us from reloading a checkpoint file if the MPI domains are different. The way we currently store the data means we could, in principle, reload the LB fluid component of the checkpoint file with a different number of MPI ranks, a different domain decomposition, and a non-waLBerla LB implementation in ESPResSo.
* we can only store in binary mode

**Comment by RudolfWeeber** [comment]
The fact that such a checkpointing freezes the MPI topology is, why I didn’t suggest this approach.

I think we should get to a point, where checkpoitns can be loaded independent of the number of mpi ranks.

 

Long term, I think, we can give up on the binary/ascii formats and just use hdf. That’s a structured format which potentially supports writing different mpi ranks in parallel, and is easily readable in Python, in case someone needs to inspect a checkpoint manually.

**Comment by RudolfWeeber** [comment]
@jngrad, can this be closed?

**Comment by jngrad** [comment]
Yes, checkpointing for LB is now working. EK checkpointing can be dealt with later when we write the new EK code for 4.3.
