### ISSUE TITLE
Walberla: Fix engine_lb

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3514]
on one mpi rank, there is a slight momentum deviation. This may be due to the changed behavior that 
dt * F/2
from the last LB time step are now included in momentum calculation.

On two mpi ranks, the test freezes.
The test is disabled at CMake level

**Comment by RudolfWeeber** [comment]
Testing single swimmer coupling steps is now possible via the last_applied_force property of lb nodes.
See test_viscous_coupling in testsuite/python/lb.py for template

**Comment by RudolfWeeber** [comment]
@christophlohrmann, I fixed the factor 8. Source positions should not be folded in lb_particle_coupling.cpp.
That may well have solved the boundary issue as well.

The momentum conservation after 100 steps test fails due to the tolerance limit. The momentum is conserved up to 1E-9. Can you please take a look at the test and make a decision whether or not that's OK.
Also, could you please clarify why the force correction term is 
particle_force * time_step rather than 0.5 * particle force * time step?

Please take the current walberla branch from my github as starting point. You can re-enable the momentum conservation test by removing the WALBERLA_TODO from the function name.

**Comment by christophlohrmann** [comment]
Thanks for the factor 8 fix. Crossing boundaries works on one MPI rank now.
1E-9 is acceptable for me.

As for the full time step:
- why I used ``reuse_forces=True``: If I don't use it, ``force_calc()`` is called the first time without LB-coupling. That means no friction for any swimmer and no additional force for the ``v_swim`` type swimmers. The active force for the ``f_swim`` swimmers gets added anyway because it is not derived from the coupling to LB. With ``reuse_forces`` at least both types are treated the same.
- Therefore, in the first halfstep, the active forces on the particles are missing.  This creates the first half of the missing momentum.
- The LB fluid is always ahead by a half step (as checked by ``test_ext_force_density()`` in ``lb.py``). It is also not affected by the ``reuse_forces`` in the first halfstep because ``force_calc()`` with coupling is called in the main integration loop before ``lb_lbfluid_propagate()``
- => in total, the fluid momentum is ahead by a full time step
