### ISSUE TITLE
MPIIO needs some improvement

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3590]
The mpiio parallel io method needs some work. Currently it only stores part of the particle information, which might be very surprising (e.g. the linear position is stored, but the orientation is dropped). I think I should either use the same selection mechanism as for the ghosts, eg make it switchable which sub structs are stored, or just always store complete particles. It's also currently possible to write dumps that can not be restored, because the positions are optional, but particles without positions can not be created.

**Comment by KaiSzuttor** [comment]
as we have already discussed in private we should either put work into mpiio or remove it and invest in reading from h5md files (which is probably the better idea).

**Comment by hirschsn** [comment]
The H5MD module can't output bonds, can it?
That was the initial idea behind MPI-IO. To have an output routine that works in parallel and can store variable-size data such as bond information for large-scale runs. Also, the format was supposed to be simple binary data to be able to parse it outside of ESPResSo. This is necessary because if one wants to evaluate large-scale runs, reading the snapshot into ESPResSo, again, and evaluating the data inside an ESPResSo python script is just too slow because of communication, etc.
Therefore, e.g. this program exists: https://github.com/hirschsn/snap-analyze which can analyze gigabyte snapshots (including gigabytes of bond information) in a matter of seconds to a few minutes.

However, the format was changed numerous times in the past by refactorings (declaring some variables "auto" so they serialized to size_t instead of int, and, most notably d3b302e77, which changes way bond data is serialized.)

An additional point of rework, that the MPI-IO module in its current state needs is that it performs index arithmetics on integers (3*i), and, thus only supports INT_MAX/3 particles.

**Comment by KaiSzuttor** [comment]
i think it would have been easier to extend the h5md implementation than reinventing the wheel and implementing a totally new binary format. parsing h5md is trivial because one can directly read it via h5py in python. so i don't see the point of mpiio...

**Comment by hirschsn** [comment]
I totally agree with you reinventing-the-wheel statement. However, iirc, the wheel was never reinvented because MPI-IO was present before HDF5 output in ESPResSo.

You can remove MPI-IO if you see no point in it. But first, please ensure that users can output bond data *and* read them in, again, *and* parse the format without ESPResSo. Which is hard, if they have to know the internals like how a BondList is serialized and how the headers that boost::iostreams, stream_buffers, etc. prepend to the data look like.

**Comment by RudolfWeeber** [comment]
>i think it would have been easier to extend the h5md implementation than reinventing the wheel and implementing a totally new binary format. parsing h5md is >trivial because one can directly read it via h5py in python. so i don't see the point of mpiio...

I think, MPI-IO was probably first, maybe in a project branch.

 

Kai, did you at some point resolve the issue with saving three-particle bonds to H5md?

#1715 is still open.

 

Before removing MPI-IO and switching to Hdf entirely, it would need to be demonstrated that the Hdf5-writer successfully handles the system sizes that Steffen is dealing with.

**Comment by KaiSzuttor** [comment]
no, i have not looked into this.

> Before removing MPI-IO and switching to Hdf entirely, it would need to be demonstrated that the Hdf5-writer successfully handles the system sizes that Steffen is dealing with.

I don't think that this needs to be checked. Hdf5 is designed to deal with large datasets. If our implementation (that is not yet there) is or will be as performant as mpi-io is a different topic.

**Comment by KaiSzuttor** [comment]
> You can remove MPI-IO if you see no point in it. But first, please ensure that users can output bond data and read them in, again, and parse the format without ESPResSo. Which is hard, if they have to know the internals like how a BondList is serialized and how the headers that boost::iostreams, stream_buffers, etc. prepend to the data look like.

Reading the file again is probably the point here. That is not implemented at all for espresso. However, i do not see the point here, since we are having the checkpointing mechanism that deals with reading a stored state of espresso.

**Comment by hirschsn** [comment]
@KaiSzuttor Does checkpointing work in parallel? Or will it transfer all data to rank 0 first?

**Comment by RudolfWeeber** [comment]
The checkpointing is not suitable for the system sizes relevant for Steffen.

**Comment by KaiSzuttor** [comment]
yes, reading and writing checkpoints always is only rank 0.

**Comment by RudolfWeeber** [comment]
I'm closing this, because we plan to implement full parallel hdf output, so wokr shoudl go there.
