### ISSUE TITLE
Add and enforce CMake formatting rules

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3591]
We should have a .cmake-format file, and enforce it in the CI. We might also consider checking
if there are source files that are not mentioned in the build system and warn about that (not sure about this one).

**Comment by KaiSzuttor** [comment]
maybe we should also have a look at [pre-commit](https://pre-commit.com). Would probably be handy and could avoid all those useless formatting commits.

**Comment by RudolfWeeber** [comment]
>maybe we should also have a look at  <https://pre-commit.com> pre-commit. Would probably be handy and could avoid all those useless formatting commits.

As a first step, we might include @jngrad’s git-style command in the maintainer folder. With this, the style checks execute in less than 3 secs, so you can actually run them more frequently. The full fix_style.sh runs for more than 1 min for me, which is too slow for frequent use.

 

Commit hooks probably place rather specific requirements on users’  environments.

**Comment by KaiSzuttor** [comment]
The advantage of ```pre-commit``` is that it only runs on changed files which is very fast.
The tool, however, is probably more useful for the espresso team that for regular users. Still I see some value here.

**Comment by mkuron** [comment]
For use by regular users, you can put it into the fix_style script that is already run by CI. For your own purposes, add pre-commit hooks to your local repository as you find useful (hooks are not part of the repository and thus cannot be pushed to a remote anyway).

**Comment by KaiSzuttor** [comment]
> hooks are not part of the repository and thus cannot be pushed to a remote anyway

it's also a tool, in case you missed that

**Comment by mkuron** [comment]
That makes no difference, it just makes it easier to share your hooks with someone else. Not too different from a shell script in the repo and symlinks. Enabling them requires manual work and they are not run server-side (e.g. when merging a pull request). It does not change anything about the general concept of git hooks. I'm not a fan of git hooks because they can make advanced git operations like rebase very annoying and produce errors that inexperienced users are unable to fix (so we definitely should not recommend that everyone enable them). Having a script that runs in CI (like fix_style) and can be run locally as desired feels like the easier and more transparent approach.
