### ISSUE TITLE
Devise an error handling strategy

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3646]
Currently error handling in the core is done by a mixture of exceptions and the runtime error methods.

It is still true that there is no easy way to get the program into a defined state after an error has occurred in an parallel program. I think it should therefore in general not be possible to continue
after an error has occurred.

I think a proper solution would be to use exceptions exclusively in the core. Those can be caught where it is known to be safe. Otherwise they will fall thru to the callback system, which then can
ensure proper MPI shutdown (via MPI_Abort) without deadlocks.

**Comment by fweik** [comment]
We might also consider using a logging system per node to get more runtime information to the user,
one _could_ e.g. use [speedlog](https://github.com/gabime/spdlog) or something similar to generate
structured output.

**Comment by jngrad** [comment]
offline discussion:

Exception mechanism in the core: functions called from Cython should `throw std::runtime_error("message");` or similar. The function must be marked as `except +` in the corresponding .pxd file, so that Cython can catch the exception and raise a Python exception. This is not possible in the following cases:
* the function is a MPI function, in which case `runtimeErrorMsg() << "message";` plus the appropriate error code are required
* the function is called by another core function: there is a risk that core caller function is part of the MPI communication, either now or in the future

These exceptions need to be checked in the testsuite using `with self.assertRaises(RuntimeError):`. The tests should also check the system isn't left in an undefined state, i.e. the exceptions are raised before values in the core are changed (8977e50c597486d).

Whenever possible, Cython should only check variable types and the core should check the variable values. This avoids unnecessary code duplication for range checking between the core and interface.

This strategy was applied progressively over the last two months: 411875aa858150, 408ca6972a872d5, cb119465ef1b5, d2e4954dcb1d7fe7, 5e4b9daf9bdc4c39

**Comment by KaiSzuttor** [comment]
We should include this in the dev guide and close this issue afterwards.

**Comment by jngrad** [comment]
This information is now part of the developer's guide, section [Software design: Exception mechanism](https://github.com/espressomd/espresso/wiki/Software-design/9871dbb93ffe304623b8fcb097eb05e9d0792dc0#Exception_mechanism).
