### ISSUE TITLE
Performance degradation since 4.1.2

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3700]
LJ benchmark with 1000 particles on one core at 0.1 volume fraction
on argali.icp with g++-6 and nvcc
From 0.27 ms/ step to 0.34 ms /step
Accoding to git bisect, this occured in 
```
# first bad commit: [80fc13562b1bf65b3c6adfc56d922a9cd75e4cff] core: Moved rotation thermostat calculation from integrator to force calc
```
The calls in the commit need to be hecked for unwanted copy operations etc. The changes intended by the commit, do not explain a 30% slow down IMO.

**Comment by fweik** [comment]
Please provide a minimal script that demonstrates the issue.

**Comment by RudolfWeeber** [comment]
>Please provide a minimal script that demonstrates the issue.

 

Pypresso Maintainer/benchmarks/lj.py –-particles_per_core 1000 -–volume_fraction 0.1

With default myconfig

**Comment by fweik** [comment]
If I remember correctly, this code adds an additional frame transformation. That could be it. Those could also probably be optimized, currently they calculate the full rotation matrix from the quaternion and the subsequently apply it, which is probably not the most effective way to do it. The absolute change you are showing here are pretty small still, about 70ns per particle, so not sure if this is worth investigating. My guess is this is only visible because there is so little else to calculate in the system...
