### ISSUE TITLE
Periodic Boundary Conditions violate equipartition theorem in molecular dynamics simulations?

### ISSUE THREAD

**Issue by jonaslandsgesell** [espressomd/espresso#372]
This paper from 2013 outlines that the equipartition theorem is violated in molecular dynamics simulations with periodic boundary conditions if the center of mass (COM) is conserved if there are no fluctuations allowed for the COM. (Maintaining the equipartition theorem in small heterogeneous molecular dynamics ensembles, http://journals.aps.org/pre/pdf/10.1103/PhysRevE.87.030101).
Especially (but not only) if there are particles of different masses there should be errors induced as the paper states. Systematic errors can be avoided by allowing the center of mass to fluctuate. Therefore bulk simulations with the mass feature enabled could be wrong.
Is it planned to introduce these fluctuations?
Maybe an adaption of the galilei-transform function does the trick already?

**Comment by uschille** [comment]
The reason for the deviations from equipartition is not the periodic boundary conditions but the smallness of the system which means that one is far away from the thermodynamic limit so neither ensemble equivalence nor equipartition are expected, in particular when there are long-range correlations in the system. It turns out that the deviations from equipartition are exactly what one would expect from theory.

**Comment by jonaslandsgesell** [comment]
Thanks I must have missed that.

**Comment by uschille** [comment]
Hi,

I think that Fatollah et al. were interested in glassy systems where the
relaxation times are long, and they were looking for a 'trick' to get
away with small systems. So in some cases that may be useful, but I'd
implement it on the script level (as you say) and not in the simulation
core, because in principle the simulation does what it's supposed to do.
There is of course a lot to think about when it comes to long-range
interactions such as electrostatics, where it is not so clear whether
ensemble equivalence holds even in the thermodynamic limit.

Cheers,
Ulf

On 07/27/2015 08:55 AM, Jonas Landsgesell wrote:
> Thanks I must have missed that.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/372#issuecomment-125114873>.

-- 
Ulf D. Schiller
Centre for Computational Science
University College London
20 Gordon Street
London WC1H 0AJ
United Kingdom

Phone: +44 (0)20 7679 5300
