### ISSUE TITLE
LB coupling should use per particle gamma

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3734]
Currently the behavior of the LB and the Langevin thermostat differ in that the latter does use per partticle gamma's and particle anisotropy, while the former only support a global, scalar friction coefficient. This shouldn't be hard to change, and would allow for anisotropic point particles with dispersity. (In principle this is also true for the per particle temperature, but this is even more of a foot gun than for Langevin, so not a big fan...)

**Comment by RudolfWeeber** [comment]
This should be done in the Walberla branch.

**Comment by RudolfWeeber** [comment]
Moderate difficulty. 
* check the lagnevin thermostat code to find out, hwo the gamma is chosen (either the system-wide default, or the one set per particle)
* Intoduce the same logic in src/grid_based_algorithms/lb_particle_coupling.cpp
* I.e, instead of the plane lattice-Boltzmann thermostat gamma should be used if no value is given on the particle, but otherwise the one from the particle.
* Note that the same coordinate transformation as for the Langevin thermostat is needed, when the particle specific friction coefficient is anisotropic.
