### ISSUE TITLE
Warnings in CUDA builds

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3797]
There are warnings in the CUDA build:

```
espresso/src/utils/include/utils/Span.hpp(88): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during instantiation of "Utils::Span<T>::Span(const C &) [with T=const double, C=std::vector<double, std::allocator<double>>, <unnamed>=std::vector<double, std::allocator<double>>, <unnamed>=std::vector<double, std::allocator<double>>]" 
espresso/src/core/electrostatics_magnetostatics/mmm-common.hpp(49): here
```
which should be fixed. Also why are warnings are not errors for CUDA?

**Comment by mkuron** [comment]
> why are warnings are not errors for CUDA?

Because `nvcc` did not support `-Werror` for a long time. Since around CUDA 9, you could specify `-Werror reorder,cross-execution-space-call`, but the supported types of warnings changed between versions. I just saw in the documentation that since CUDA 10.2 there is `-Werror all-warnings`, which would be worth adding to our flags (of course with an appropriate version check).

The Clang build has `-Werror`, but its `__host__`/`__device__` calling rules are more relaxed, so it does not print an error.
