### ISSUE TITLE
integrator_npt test fails with 4 cores

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#3800]
with
```
AssertionError: 0.29441185680606063 != 0.32 within 0.02 delta
```
while it passes with fewer nodes (4 is the maximum allowed).

This is a bug, the result should be independent of the number of ranks.

**Comment by fweik** [comment]
Apparently this was caused by merging the topology PR. I don't know how to address this.

**Comment by jngrad** [comment]
The test was recently made quicker by sampling for 10'000 steps instead of 40'000 ([`749108b7`](https://github.com/espressomd/espresso/commit/749108b7ec5d4cc06ada35e6a8731bbfcd889b76#diff-3f6abb429df9fb28f32692241cc427af)). According to my stats (7f7dda5844), 20'000 was a minimum to avoid random failures in CI. We could increase the delta value. The compressibility statistic changed significantly for no clear reason when we moved from the Mersenne Twister to Philox for NpT, so I wouldn't worry too much.

**Comment by fweik** [comment]
But why would the result depend on the number of ranks?

**Comment by fweik** [comment]
FYI 30k samples work, 20k are not enough. This looks still suspicious to me, but I don't that we can make progress here without proper tests...

**Comment by RudolfWeeber** [comment]
Can no longer reproduce. Tried 5 different processor counts

**Comment by fweik** [comment]
Did you check if the tests fails or if the result depends on the number of cores?

**Comment by jngrad** [comment]
The issue is reproducible. Changing the skin or number of MPI ranks introduces a small deterministic deviation. This leads to error accumulation, which becomes problematic after 10k steps.

MWE:
```python
import numpy as np
import espressomd
data = np.genfromtxt("testsuite/python/data/npt_lj_system.data")
system = espressomd.System(box_l=3 * [5.86326165], time_step=0.001)
system.cell_system.skin = 0.25
system.part.add(pos=data[:, :3], v=data[:, 3:])
system.non_bonded_inter[0, 0].wca.set_params(epsilon=1., sigma=1.)
system.thermostat.set_npt(kT=1.0, gamma0=2., gammav=0.004, seed=42)
system.integrator.set_isotropic_npt(ext_pressure=2.0, piston=0.0001)
system.integrator.run(20000)
print(np.around(system.part[:].pos[:4,:], 2))
print(np.around(system.box_l, 2))
```
Output:
```
$> mpiexec -n 1 ./pypresso integrator_npt.py
[[ 2.94  1.07  2.11]
 [ 0.57  3.93 11.42]
 [ 0.58  4.11  2.08]
 [ 0.08  1.19  5.26]]
[5.64 5.64 5.64]

$> mpiexec -n 2 ./pypresso integrator_npt.py
[[ 3.35  1.38  1.11]
 [ 0.22  1.25  9.94]
 [ 1.17  3.59  2.96]
 [ 0.77 -1.08  4.11]]
[5.71 5.71 5.71]
```

**Comment by jngrad** [comment]
Printing `nptiso.p_inst` and `nptiso.p_diff` in function `velocity_verlet_npt_finalize_p_inst()` reveals a change at the 14th decimal place after 2600 integration steps in the 1 vs. 2 MPI ranks cases. This only becomes an issue after 4000 integration steps, at which point the box size is different at the 14th decimal place. The error keeps increasing after that.

I think this is just a manifestation of numerical instability in the summation. The virial stress is calculated with a sum over all particles, but the order of the particle depends on the number of MPI ranks. The numerical error in the instantaneous pressure is then propagated back to all particles when the NpT barostat rescales the box, which causes the MD trajectory to diverge.

There is no need to address this issue, since a Kahan summation would make the NpT code even slower and would only delay the time at which the MD trajectory starts to diverge. This instability is also negligible compared to the instability one gets by running two simulations on 1 MPI rank with the same initial positions and velocities for the particles, but by inserting them in the system in a different order: the instantaneous pressure is different at the 2nd decimal place at the first time step.
