### ISSUE TITLE
Tutorial 1: LJ

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3818]
* the overlap removal should be done using steepest descent

* the odd indexing
```
for i in range(1,n+1)
```
in the sampling loop needs to be changed to zero-based

* The tutorial assumes without justification that the energy time series is uncorrelated. 
At the very least, an acf of the data needs to be plotted so the auto-corrleaiton time can be read  visually. It needs to be stated that the effective sample count in the error calculation is for a minimum sampling distance of two auto-correlation times.
I don't think, we need to do the full underlying math in the first tutorial.

* The concept of observables and accumulators needs to be explained in 1-2 sentenes.

**Comment by schlaicha** [comment]
We need to add some documentation for the tutors mentoring the tutorials. I suggest we use simple markdown files for these instructions. Would `doc/tutorials/01-lennard_jones/NotesForTutor.md` be the right place to put this? We should then unify this for all tutorials...

**Comment by schlaicha** [comment]
A note on the values for the density/temperature:
* A reduced density of 0.5 that was previously used is **always** metastable, i.e. it wants to phase separate.
  This leads to the fact that NVE/NVT simulations yield different RDFs (and probably more observables differ) and the failing comparison of the fitted RDF expression in Tutorial 01.
* Using a density of 0.75 and reasonable temperature for liquid argon as given in Verlet's 1967 paper fixes all issues.

The working RDF comparison is now in 697bda0e.

What is still to do:
~~[ ] MSD / diffusion coefficient~~
[x] Energy / error estimate plus long-range contribution -> compare with energy in Verlet's 1967 paper

**Comment by schlaicha** [comment]
After offline discussion with various ICP members we decided to remove the MSD part in the LJ tutorial because
* simulations are performed with a Langevin thermostat, this the measurable diffusion coefficient is only given by the friction coefficient and not the LJ fluid
* NVE simulations would be an alternative but make the tutorial
  * more complicated
  * the use of a thermostat should be shown in the first tutorial
* diffusion constants are calculated via MSD in 04-lattice_boltzmann

The working tutorial is in c9e2817c and 0d7726a1 fixes the test cases.

Remaining todo:

[ ] add useful test for the RDF (current one did not detect visible differences)
[ ] add test for the potential energy/particle

**Comment by jngrad** [comment]
Concerning the RDF, you can simply reduce the test tolerance from 2.5% to e.g. 0.5%, or lower, depending on well the ESPResSo RDF agrees with the paper.
