### ISSUE TITLE
Slight error in Gay-Berne Potential

### ISSUE THREAD

**Issue by Kischy** [espressomd/espresso#3834]
I think there is a slight error in the Gay-Berne Potential calculation in code and documentation:

The term (see http://espressomd.org/html/doc4.1.3/inter_non-bonded.html#gay-berne-interaction)
![grafik](https://user-images.githubusercontent.com/42995291/88912403-80a14480-d25f-11ea-9d69-c217e8def714.png)
should really be
![grafik](https://user-images.githubusercontent.com/42995291/88912643-dc6bcd80-d25f-11ea-8f32-28fbba0b54e0.png). 
Note the exponent.

This is accoring to the original equations in "J. G. Gay, B. J. Berne, Modification of the overlap potential to mimic a linear site–site potential, J. Chem. Phys. 1981, 74, 3316."

The equations in the original paper are:
![grafik](https://user-images.githubusercontent.com/42995291/88912756-0a511200-d260-11ea-9fc6-8a8b91079aec.png)
and
![grafik](https://user-images.githubusercontent.com/42995291/88912782-150ba700-d260-11ea-8bc0-f4970af8a88b.png).

Am I correct or am I overlooking something?

**Comment by jngrad** [comment]
I think you're right. However, a quick literature search reveals we are not the only one who dropped the nu exponent on epsilon0:
- Berardi et al. 1993 eqn 4 ([doi:10.1039/FT9938904069](https://doi.org/10.1039/FT9938904069))
- Rull et al. 2017 eqn 4 ([doi:10.1080/00268976.2016.1274437](https://doi.org/10.1080/00268976.2016.1274437))
- Rull et al. 2017 eqn 4 ([doi:10.1021/acs.langmuir.7b02347](https://doi.org/10.1021/acs.langmuir.7b02347))
- Hekmatzadeh et al. 2020 eqn 3 ([doi:10.1016/j.chemphys.2020.110792](https://doi.org/10.1016/j.chemphys.2020.110792), [arXiv:2004.05056](https://arxiv.org/abs/2004.05056))
- Berardi et al. 1995 eqn 6 ([doi:10.1016/0009-2614(95)00212-M](https://doi.org/10.1016/0009-2614(95)00212-M))
- Berardi et al. 1996 eqn 6 ([doi:10.1016/S0009-2614(98)01090-2](https://doi.org/10.1016/S0009-2614(98)01090-2))
- Luckhurst et al. 2006 eqn 4 ([doi:10.1080/02678299008047361](https://doi.org/10.1080/02678299008047361))
- Bates et al. 1999 eqn A5 ([doi:10.1063/1.478563](https://doi.org/10.1063/1.478563))
- Cleaver et al. 1996 eqn 8 ([doi:10.1103/PhysRevE.54.559](https://doi.org/10.1103/PhysRevE.54.559))
- Miguel et al. 1996 eqn 3a ([doi:10.1063/1.472292](https://doi.org/10.1063/1.472292))

I couldn't find papers citing the Gay et Berne 1981 paper that included the nu exponent. Since epsilon0 is a constant, its nu exponent only rescales the potential and force. I would guess that's the reason why GB papers simply leave the exponent out.

We should add a citation to Gay et Berne 1981 plus a note that we use the convention of epsilon0 without exponent that is prevalent in the GB literature, in both the Sphinx documentation and the C++ source code.

**Comment by Kischy** [comment]
Ok, sounds good.

**Comment by jngrad** [comment]
Thanks for pointing out that discrepancy. I'll open a PR.
