### ISSUE TITLE
cannot build if default config is used and cuda enabled

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3836]
steps to reproduce:
```
cmake .. -DWITH_CUDA=ON
make
```

**Comment by fweik** [comment]
This should have priority.

**Comment by fweik** [comment]
It should in that context also be clarified why espresso handles the dependencies of the SD upstream library.

**Comment by jngrad** [comment]
offline discussion with @KaiSzuttor: there are two orthogonal issues in this issue:
- feature `EXPERIMENTAL_FEATURES` should be a CMake flag rather than a macro because CMake needs to know whether a library is marked as experimental
- SD only works on CUDA 9+, while we support CUDA 8 through the Clang compiler (cannot be resolved with the current build system, unless we have `-DWITH_SD_CPU` and `-DWITH_SD_GPU` CMake flags plus `SD_CPU`/`SD_GPU` macros in `myconfig.hpp`); we could drop support for CUDA 8 in 4.2

SD revealed that when it comes to features selection, our build system was prone to cyclic dependencies. This needs to be addressed, independently of the fate of SD.

**Comment by fweik** [comment]
> feature EXPERIMENTAL_FEATURES should be a CMake flag rather than a macro because CMake needs to know whether a library is marked as experimental

Can you explain why this is? I don't follow

**Comment by jngrad** [comment]
> > feature EXPERIMENTAL_FEATURES should be a CMake flag rather than a macro because CMake needs to know whether a library is marked as experimental
> 
> Can you explain why this is? I don't follow

CMake appends `STOKESIAN_DYNAMICS_GPU` to the myconfig file. But `STOKESIAN_DYNAMICS_GPU` is not self-contained, it depends on `EXPERIMENTAL_FEATURES`. This means the espresso build will fail eventually, usually after many dependencies of `EspressoCore` have been built already:
```
[  1%] Built target sd_cpu
[  5%] Built target EspressoShapes
[  5%] Built target version
[  5%] Built target myconfig
[  7%] Built target generate_config_features
[  7%] Built target check_myconfig
Scanning dependencies of target EspressoConfig
[  7%] Building CXX object src/config/CMakeFiles/EspressoConfig.dir/config-features.cpp.o
/work/jgrad/espresso-fork-PR/build/src/config/config-features.cpp:23:2: error: #error Feature MY_STOKESIAN_DYNAMICS requires EXPERIMENTAL_FEATURES
 #error Feature MY_STOKESIAN_DYNAMICS requires EXPERIMENTAL_FEATURES
  ^~~~~
```

**Comment by fweik** [comment]
This is all a consequence from trying to do feature configuration from cmake, while features are not a cmake concept.
This is e.g. why your proposed solution does not scale, what if `STOKESIAN_DYNAMICS_GPU` would depend on another
feature? This has to become a cmake option too?

**Comment by jngrad** [comment]
is 356f878a7 what you have in mind?

**Comment by KaiSzuttor** [comment]
The build issue mentioned above is gone by #3837. The underlying issue however is not resolved yet.
