### ISSUE TITLE
Check documentation for bad practices

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#3854]
E.g.:
``` python
from espressomd import polymer
```
in ```doc/sphinx/particles.rst```.

Polluting the namespace with "polymer" is probably not the best idea.

**Comment by KaiSzuttor** [comment]
maybe we should check https://gist.github.com/sloria/7001839

**Comment by fweik** [comment]
It might be worthwhile to look for espresso usage on github, to find patterns that people use, e.g.
have a look at <https://github.com/search?q=import+espressomd&type=Code> . I did not look for
this previously, and this apparently finds some use scripts...

**Comment by jngrad** [comment]
This is a suitable task for a coding day. One needs to read through the samples, tutorials and Sphinx documentation to spot anti-patterns and python2-specific syntax. In addition to what was already mentioned above, here are a few more things to look out for.

The following statements:
```python
import espressomd
import espressomd.shapes
from espressomd import electrostatics
```
can be changed to:
```python
import espressomd.shapes
import espressomd.electrostatics
```
because the statement `import X.Y.Z` makes `X`, `X.Y` and `X.Y.Z` available in the current scope. There are ~25 such examples in ESPResSo according to the [lgtm report](https://lgtm.com/projects/g/espressomd/espresso/alerts/?mode=list&lang=python) at the time of writing. Note that `import X.Y.Z as T` only makes `T` visible in the current scope; this is acceptable for commonly used modules like `import matplotlib.pyplot as plt`. There are wildcard imports in the documentation that absolutely need to be removed, e.g. `from espressomd import *` in `visualization.rst`.

There are places where f-strings can replace the old format syntax, e.g. `assert err < 1, f'Error too large: {val:.2f}'` instead of `assert err < 1, f'Error too large: {:.2f}'.format(val)`. Sometimes people use reserved names as variable names, namely `id`, `sum`, `type`, `object`, `dict`, `list`. They should be renamed to e.g. `idx`, `total`, `ptype`, `obj`, `map`, `array`, excepted in the signatures of Cython functions (to avoid breaking API).

The code examples written inside docstrings should also be checked, they appear in page [espressomd.html](https://espressomd.github.io/doc/espressomd.html). To quickly navigate between code blocks in an HTML page, one can use the following Javascript bookmarklet: [CodeBlocks.js](https://github.com/espressomd/espresso/files/6460320/CodeBlocks.js.txt).

**Comment by jngrad** [comment]
There are a few try/except anti-patterns that look like this:
```python
try:
    from espressomd.virtual_sites import VirtualSitesInertialessTracers, VirtualSitesOff
except ImportError:
    pass

@utx.skipIfMissingFeatures('VIRTUAL_SITES_INERTIALESS_TRACERS')
class VirtualSitesTracers(ut.TestCase):
    system = espressomd.System(box_l=[1, 1, 1])
    def test(self):
        self.system.virtual_sites = VirtualSitesInertialessTracers()
        ...
```
They can be rewritten as:
```python
import espressomd.virtual_sites

@utx.skipIfMissingFeatures('VIRTUAL_SITES_INERTIALESS_TRACERS')
class VirtualSitesTracers(ut.TestCase):
    system = espressomd.System(box_l=[1, 1, 1])
    def test(self):
        self.system.virtual_sites = espressomd.virtual_sites.VirtualSitesInertialessTracers()
        ...
```
