### ISSUE TITLE
Simulating ionization reactions on surfaces

### ISSUE THREAD

**Issue by dpo854** [espressomd/espresso#3855]
Hi All,
I am trying to study the ionization of chemical groups(acids in this case) constrained to be on solid surfaces, which are in contact with an electrolyte. I can do this manually by changing the type of the reactant to that of the product, which is the charged state, and simultaneously bringing an H+ ion into the system, with a probability that would depend on the reaction constant, the chemical potential of the ion and their absolute numbers (the exact formula is of little relevance to the post here). My question is since this probability depends on the change in system energy upon the whole move, does espressomd allow for the computation of energy without integration(that is the energy just after the insertion without any system evolution happening)? Secondly, how can this be tackled with the reaction ensemble(RE)? I know the documentation briefly makes a reference to such cases, where only the identity of the reactant needs to be changed without it having to be removed. But I am unable to figure out how to effect such a move using RE. 

Thanks,
Debadutta Prusty

**Comment by jonaslandsgesell** [comment]
Hi Debadutta,

Confining reacting groups to surfaces is simple! You simply need to call the add(...,fix=True) function for the particles which ought be fixed first and flag them with fix=True on creation.
The reactions then need to be setup such, that the reactand type which you want to replace with a product type are in the corresponding positions of the particle type lists:

... reactand_types=[HA], product_types=[A-, H+],...
This will replace HA particles (at the place of the HA particles) with A- particles and additionally create H + particles (how many is determined by the product_coefficients and reactand coefficients list which hold the absolute values of the corresponding stochiometric coefficients).

If you would write ... product_types=[H+, A-] instead, then HA particles would be replaced with H+ particles (in place) and A- particles would be added randomly in the system. The order of entries in the list matters here!

The charge of the particle types is submitted to the reaction ensemble in the add_reaction() function.

Typically, you also want to confine the space in which the of H+ particles are created. You can do this with the commands 

* RE.set_cylindrical_constraint_in_z_direction( center_x, center_y, radius_of_cylinder)
* RE.set_wall_constraints_in_z_direction(slab_start_z, slab_end_z)

But then you also need to change the volume used in the reaction ensemble algorithm via:

RE.set_volume(volume)

And if you use a MD integrator you also need to place constraints for the cylinder/ walls you want to act on the H+ ions. Otherwise the MD integrator will propagate your particles out of the region you wanted them to be created in.

The energy is recalculated by the reaction ensemble prior and after every attempted reaction such that the acceptance probability correctly accounts for the change in potential energy as it is required in the reaction ensemble or constant pH ensemble (see https://www.tandfonline.com/doi/abs/10.1080/08927020801986564)

Potentially, you will also want to make use of an electrostatic solver with partial periodicity like ELC or MMM2D, MMM1D... 

PS: If you only want to change one type to another one you can do it via adding a reaction with ...reactand_tpyes=[type_A], product_types=[type_B]... This will replace A types with B types in place.
In any case the added reaction has to be electroneutral. If you really know what you are doing you can also make use of non_electroneitral reactions via turning the electroneutrality check for the reactions off (but to my experience this never made sense from a physical point of view for macroscopic systems).

We simulated reacting groups confined to wall-like surfaces or to the surface of colloids ( raspberry particles) in Jan Finkbeiners Bachelor thesis making use of the reaction ensemble in espresso. You can ask @jrfinkbeiner for more details or Prof. Holm for Jan's thesis.
