### ISSUE TITLE
Some tests fail on Fedora Rawhide 

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3905]
On Fedora Rawhide:
```
The following tests FAILED:
	 23 - coulomb_cloud_wall (Failed)
	 71 - domain_decomposition (Failed)
	 83 - coulomb_cloud_wall_duplicated (Failed)
	109 - cluster_analysis (Failed)
Errors while running CTest
```

Build log attached: [build_x86_64.log.txt](https://github.com/espressomd/espresso/files/5255428/build_x86_64.log.txt)

**Comment by jngrad** [comment]
According to the build log, it's for ESPResSo 4.1.3 on Fedora 34. The tests pass with MPICH, but some fail with OpenMPI 4.0.5 compiled with UCX. Excerpt of the errors:
```
 87/147 Test  #71: domain_decomposition ..............................***Failed    2.08 sec
[1600672054.218898] [buildvm-x86-10:1118475:0]           sock.c:344  UCX  ERROR recv(fd=30) failed: Bad address
[1600672054.218963] [buildvm-x86-10:1118474:0]           sock.c:344  UCX  ERROR recv(fd=28) failed: Connection reset by peer
[1600672054.222217] [buildvm-x86-10:1118475:0]           sock.c:344  UCX  ERROR sendv(fd=-1) failed: Bad file descriptor
terminate called after throwing an instance of 'boost::wrapexcept<boost::mpi::exception>'
  what():  MPI_Test: MPI_ERR_INTERN: internal error
 97/147 Test  #83: coulomb_cloud_wall_duplicated .....................***Failed    4.40 sec
Complex value is not zero (i=0,data=256.326)!!!
 43/147 Test  #23: coulomb_cloud_wall ................................***Failed    2.27 sec
Complex value is not zero (i=0,data=634.005)!!!
118/147 Test #109: cluster_analysis ..................................***Failed    2.36 sec
ERROR: No cluster criterion defined
```
I'm not familiar with the cluster analysis error.

The other 3 errors are already described in #3853 for Fedora 33 in the subsection for OpenMPI.

**Comment by junghans** [comment]
Still the same as of today: [build.log.txt](https://github.com/espressomd/espresso/files/5379495/build.log.txt)

**Comment by jngrad** [comment]
I tried again with Fedora 34 with OpenMPI 4.0.4 and UCX 1.9.0 compiled from sources and still have 39 tests failing. These tests don't fail with OpenMPI compiled from sources without UCX.

I also just tried with Fedora 34 with MPICH 3.3.2 and UCX 1.9.0 compiled from sources and have 72 failing tests, but there it's only one type of error:
```
[1602701883.537030] [c954e24c865b:5111 :0]       mm_posix.c:162  UCX  ERROR Not enough memory to write total of 4292720 bytes. Please check that /dev/shm or the directory you specified has more available memory.
[1602701883.537309] [c954e24c865b:5111 :0]        uct_mem.c:132  UCX  ERROR failed to allocate 4292720 bytes using md posix for mm_recv_desc: Out of memory
[1602701883.537341] [c954e24c865b:5111 :0]          mpool.c:191  UCX  ERROR Failed to allocate memory pool (name=mm_recv_desc) chunk: Out of memory
[1602701883.537369] [c954e24c865b:5111 :0]       mm_iface.c:644  UCX  ERROR failed to get the first receive descriptor
Abort(1094031) on node 1 (rank 1 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(586).....: 
MPID_Init(447)............: 
MPIDI_NM_mpi_init_hook(67):  ucx function returned with failed status(ucx_init.h 67 MPIDI_NM_mpi_init_hook No resources are available to initiate the operation)
```

I don't know if the issue is in espresso or in UCX, and also don't know how to investigate it further. Unless Fedora provides an OpenMPI package without UCX, you will likely need to drop support for OpenMPI when packaging espresso.

**Comment by junghans** [comment]
@opoplawski

**Comment by opoplawski** [comment]
I would check/file issue here: https://github.com/openucx/ucx/issues
There may also be ways to disable UCX in openmpi at runtime.  I would ask them.  Also, I'm doing `export UCX_TCP_PUT_ENABLE=n` in the netcdf package to work around https://github.com/openucx/ucx/issues/5535.  But that has a different error message so YMMV.

**Comment by jngrad** [comment]
I already looked into UCX tickets but couldn't find anything similar. Opening a ticket is not really helpful, because we have three classes of MPI+UCX issues here, for which we cannot write a minimal non-working example:
* reproducible ones in espresso FFT code that hasn't been maintained for a while and is planned to be replaced by FFTW, but not before espresso 4.3
* reproducible ones that involve our custom MPI visitor pattern infrastructure, which has been the subject of regular discussions in our team for almost a year now; it's not yet clear when and how we are going to replace it
* random runtime errors in OpenMPI+UCX and MPICH+UCX that depend on the environment -> cannot be investigated by GDB

This random runtime error seems to follow a pattern. I'll let you know in a few hours if there's a way to reproduce it reliably.

**Comment by jngrad** [comment]
Alright, the 39-72 random MPI+UCX errors were actually caused by hyperthreading on my AMD Ryzen Threadripper.

Espresso 4.1.3 compiles and passes all tests with [MPICH 3.3.2 + UCX 1.9.0 compiled from sources](https://github.com/espressomd/espresso/files/5385091/Dockerfile-34-mpich-ucx-190.txt) and [OpenMPI 4.0.4 + UCX 1.9.0 compiled from sources](https://github.com/espressomd/espresso/files/5385092/Dockerfile-34-openmpi-ucx-190.txt). The issue comes from OpenMPI 4.0.4 + UCX 1.8.1.

**Comment by jngrad** [comment]
Given the frequency at which OpenMPI and OpenMPI+UCX breaks the espressomd package on Fedora Rawhide, the resources it takes us to investigate such issues, and the difficulty of extracting a minimal working example from ESPResSo's custom MPI infrastructure when filing a bug report to the OpenMPI and UCX projects, the ESPResSo core team decided it would no longer be able to offer support for MPI-related issues reported from the development branches and latest releases of Fedora/CentOS/OpenSUSE. You can still open tickets here, as they help us know which OpenMPI versions are incompatible with ESPResSo, but they will be closed after a period of inactivity. If OpenMPI builds keep failing, you should consider dropping support for OpenMPI and only release ESPResSo for MPICH, or if that option is available to you, only build the package for stable releases rather than development releases.

Please note that we are not putting your efforts into question, and we have nothing against Fedora's fast development cycle. We understand the importance of filing bug reports to MPI developers, just like we value bug reports filed here, including yours from Rawhide. Unfortunately, ESPResSo's design is not suitable for MPI bug detection & characterization, and our team needs to give priority to other tasks.

**Comment by junghans** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1889614

**Comment by junghans** [comment]
Ok, in conclusion, I exclude the test on openmpi on rawhide for now.

@jngrad could you guys merge this patch for upcoming gcc-11 release:
https://src.fedoraproject.org/rpms/espresso/blob/master/f/espresso-gcc11.patch

**Comment by jngrad** [comment]
@junghans I tried to apply the patch to the 4.2 line so that you could use a PR as patch in the specfile, but `src/script_interface/ParallelScriptInterface.hpp` no longer exists in 4.2. I'm afraid you will need to maintain this patch until the 4.2.0 release.

We can no longer maintain the 4.1 line because we are currently focusing our efforts on the 4.2 and 4.3 releases. The CI infrastructure for the 4.1 line is also no longer viable. Some of the CI jobs had to be removed from the pipeline in 4.1.4 due to timeout issues and flaky tests, and we only have 3 machines left that can run the QEMU jobs. Many of the docker images can no longer be regenerated due to incompatible software (two QEMU images) and expired software licenses (Intel image).

I hope we'll be able to solve these header include issues in time for 4.2 (#3977).

**Comment by junghans** [comment]
No problem, just do a build on rawhide with gcc-11 and these issues will pop up again, they aren't hard to fix anyway.

**Comment by jngrad** [comment]
Could you share with me how you set up gcc-11 on Rawhide? I couldn't find it in the Fedora packages, was not able to compile it from sources (`gcc/read-md.c:1043: undefined reference to 'operator delete(void*, unsigned long)'`), and with [jwakely/gcc-latest](https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/), ESPResSo 4.1.4 builds without error messages (maybe gcc-c++11 is using libraries from gcc-10.2).

**Comment by junghans** [comment]
@jwakely, how you get gcc-11 on rawhide?

**Comment by jwakely** [comment]
Build from source. My gcc-latest COPR has been failing to build for rawhide for weeks, I don't know why and haven't looked into it.

**Comment by jngrad** [comment]
ok I finally managed to build GCC 11 from sources thanks to their mailing list thread [Unable to compile - undefined reference to operator new, delete](https://gcc.gnu.org/legacy-ml/gcc-help/2018-03/msg00017.html), and could reproduce the compiler error for `src/utils/include/utils/NumeratedContainer.hpp`. This will be helpful when fixing missing includes in the upcoming 4.2 release.

**Comment by jwakely** [comment]
Sorry if it's no use now, but the issue with https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/ is fixed and you can now get an up-to-date gcc-11 snapshot for Fedora rawhide (or F33) from there. It will install under `/opt/gcc-latest` rather than replace the system `gcc`, so run `/opt/gcc-latest/bin/g++` and use either `-Wl,-rpath,/opt/gcc-latest/lib64` or `LD_LIBRARY_PATH=/opt/gcc-latest/lib64` to find the new `libstdc++.so` library.
