### ISSUE TITLE
Coulomb energy kernel is executed in systems without Coulomb

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3923]
According to perf output. Probably the conditional in energy_calc() needs to be checked

**Comment by jngrad** [comment]
How much of a performance drop did you measure? Looking at the code, it should only be the overhead of a function call + traversal of a switch statement. We could add an `if(coulomb.method)` guard in `energy.cpp` to skip that overhead, although it would further increase coupling between the core and the `electrostatics_magnetostatics` module.

**Comment by jngrad** [comment]
`gdb` shows that the `energy_calc_local()` function calls `Coulomb::calc_energy_long_range()` once, from which we return very quickly (in about 4 steps) because none of the switch cases are a match. `valgrind` shows that the Coulomb function takes 0.00% of the total runtime. `perf` shows 0.00% too. In fact, `perf` on ESPResSo built with `-O3` reports that `energy_calc_local()` spends 50% of the time in a for loop for the kinetic energy, and 50% of the time in another for loop (maybe the non-bonded energy kernels). The assembly for `energy_calc_local()` doesn't display when building with `-Og` for some reason, but the report still shows that 87% of the time is spent in the non-bonded energy kernels.

Maybe your report misattributed the time spent in the short-range loop function call to the next function call, which is the Coulomb energy kernel. There is a known issue in `perf` where one slow assembly instruction is counted in the time of a fast instruction that immediately follows it. Not sure if this also happens with function calls, though. For reference, here is a MWE:

```c++
#include <cstdio>
int main() {
  int a = 100'000'000;
  int t = 0;
  for (int i = 1; i < 100'000'000; ++i) {
    int u = a % i;
    t += static_cast<int>(u == 3);
  }
  printf("%i\n", t);
  return 0;
}
```
```sh
g++ -O3 -std=c++14 -fno-exceptions -fno-rtti mwe.cpp
perf record --call-graph dwarf ./a.out
perf report -g 'graph,0.5,caller'
```
Output:
```
       │18:┌─>mov     %esi,%eax
       │   │  cltd
       │   │  idiv    %ecx
 74.12 │   │  xor     %eax,%eax
  0.06 │   │  cmp     $0x3,%edx
  7.83 │   │  sete    %al
 13.31 │   │  add     $0x1,%ecx
       │   │  add     %eax,%r8d
  4.68 │   │  cmp     $0x5f5e100,%ecx
       │   └──jne     18
```
The time of the `idiv` is transferred to the following `xor` instruction.
