### ISSUE TITLE
Mention Cmake version requirement and pip3 install --user

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3946]

**Comment by jngrad** [comment]
Regarding documenting version requirements: I'm not aware of a way to enforce synchronization between the docs and CMake. For example, in 4.2:
https://github.com/espressomd/espresso/blob/b75be6fa9a876230cca03bac3001ff11ed4a031d/CMakeLists.txt#L172
https://github.com/espressomd/espresso/blob/b75be6fa9a876230cca03bac3001ff11ed4a031d/doc/sphinx/installation.rst#L63

It's probably not possible to do automatically, because some version requirements depend on the architecture of the target machine. For those, I'm not sure if we should document conservative estimates, i.e. the highest minimal version required in the build system, or instead document the lowest minimal version required.

**Comment by KaiSzuttor** [comment]
I still think we should drop mentioning specific versions in the documentation
