### ISSUE TITLE
Avoid symbols exisitng in several shared objects

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3968]
currently, the Python interface contains several Cython-compiled modules which are linked against EspressoCore.
Ghis leads to symbols existing several times, which in trun can lead ton undefined behavior.

**Comment by fweik** [comment]
Are you sure this is really the case? Can you show an example?

**Comment by RudolfWeeber** [comment]
>Are you sure this is really the case? Can you show an example?

 

Make the Walberla instance in lb_walberla_instance.cpp a unique_ptr ore seomthing else which will be destructed at end of program.

The references on Walberla’s custom shared pointers will be miscounted.

 

This is not new though, just the conclusion from the discussion at the time, as I understood it.

 

The issue probably only arises with non-trivial globals.

**Comment by jngrad** [comment]
I'm not convinced the symbols appear in several objects. The symbol seems to only exist in `EspressoCore.so`:
```
$ nm -D src/core/EspressoCore.so | grep LBWalberlaBase | c++filt
0000000000289210 T mpi_lb_sanity_checks_local(LBWalberlaBase const&, LBWalberlaParams const&, double)
0000000000289610 T mpi_activate_lb_walberla_local(std::shared_ptr<LBWalberlaBase>, std::shared_ptr<LBWalberlaParams>)
0000000000289ba0 W std::shared_ptr<LBWalberlaBase>::~shared_ptr()
0000000000289ba0 W std::shared_ptr<LBWalberlaBase>::~shared_ptr()
$ nm -D src/script_interface/ScriptInterface.so | grep LBWalberlaBase | c++filt
                 U mpi_activate_lb_walberla_local(std::shared_ptr<LBWalberlaBase>, std::shared_ptr<LBWalberlaParams>)
$ nm -D src/python/espressomd/lb.so | grep LBWalberlaBase | c++filt
(nothing)
```

The bug is reproducible with commit bf6609db0c88 in a docker image on `seraue`. It's not reproducible outside docker on `seraue` or `lama`. It only happens when the python script instantiates a LB actor and adds VTK writers to the LB actor. You can see the full stack trace in [logfile 300304](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/300304), but here is the relevant part:
```
build/src/walberla_bridge/WalberlaBridge.so   walberla::vtk::VTKOutput::~VTKOutput()
build/src/walberla_bridge/WalberlaBridge.so   std::_Sp_counted_ptr<walberla::vtk::VTKOutput*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
build/src/walberla_bridge/WalberlaBridge.so   walberla::LBWalberlaImpl::~LBWalberlaImpl()
build/src/walberla_bridge/WalberlaBridge.so   std::_Sp_counted_ptr_inplace<walberla::LBWalberlaImpl, std::allocator<walberla::LBWalberlaImpl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
build/src/core/EspressoCore.so                std::shared_ptr<LBWalberlaBase>::~shared_ptr()
```

The waLBerla logger seems to corrupt the stack trace in GDB, so I didn't investigate it further. To me, this looks more like the well-known reference-counting bug that lead to a double free in the early days of the waLBerla integration, although in a different form. Here it happens even on MPI 1 rank, and it only happens when the custom shared pointer is allocated in an object managed by a `std::shared_ptr` that lives until normal program termination.

To me, this looks like the `VTKOutput` shared pointer is already deallocated (and its reference count an undefined value) by the time the `LBWalberlaImpl` shared pointer is being deallocated. Maybe the custom shared pointer implementation in waLBerla expires too early, leading to a race condition. The solution I came up with was to automatically clear the list of actors, and hence the global `LBWalberlaImpl` shared pointer, when the python `System` object is garbage collected (e0b198fd2166d). This way, the reference count of the `LBWalberlaImpl` shared pointer is 1 on each MPI rank during normal program termination.

This solution might not work if we have a need to share ownership of the `LBWalberlaImpl` pointer with another global variable, or with another script interface object that is not an actor and whose lifetime extends up to normal program termination.

**Comment by jngrad** [comment]
There is still an edge case where the `std::shared_ptr` might fail: if developers introduce a regression in such a way that the LB deactivation throws an exception in python or in the core, we'll have a ref count of 2 (once in the script interface object, and once in the global variable), and the bug will resurface. To solve that issue, I've now changed the type of the core global variable from `std::shared_ptr<LBWalberlaBase>` to `std::weak_ptr<LBWalberlaBase>` (e99a62d47cf4). This is a non-owning reference, just like the old raw pointer implementation. I have locally backported that change to the last commit where the bug was present (bf6609db0c88d1d9d8) and can confirm the bug was gone.
