### ISSUE TITLE
Can BROWNIAN_PER_PARTICLE and LANGEVIN_PER_PARTICLE be united?

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4008]
What we actually are switchting is, whether friction and temperature are particle specific. This should (and will) be also usable) with Walberla LB.

My suggestion would be 
* use a common THERMOSTAT_PER_PARTICLE or THERMOSTAT_PARAMS_PER_PARTICLE which turns on the data members (and is therefore performance relevant)
* If it's on, thermostats should use it
* Maybe remove kT per particle (I'm not aware of a case where that makes sense)

Otherwise, we end up with
£ifdef BROWNIAN_PER_PARTICLE || LANGEVIN_PAR_PARTICLE || LB_PER_PARTICLE
in many places.

**Comment by RudolfWeeber** [comment]
Came up during review of #3999.

**Comment by jngrad** [comment]
Related to #3734

**Comment by jngrad** [comment]
ESPResSo meeting discussion: the per-particle temperature was introduced for visualization purposes and isn't used in simulations, can be removed.

**Comment by jngrad** [comment]
@KonradBreitsprecher do you remember by any chance why Drude particles are set with a per-particle temperature of 0? The documentation doesn't explain why it is necessary, and we would like to remove the per-particle temperature feature. From what I understand, the per-particle temperature of 0 is not necessary since the per-particle gamma is already zero for Drude, in which case the Langevin thermostat is not applied to the Drude particles and the Brownian thermostat is undefined (division by zero). The trajectory of a Langevin simulation with Drude particles is identical with and without the per-particle temperature.

**Comment by KaiSzuttor** [comment]
in the best of all worlds you can just remove it and see if the drude tests still pass.

**Comment by KonradBreitsprecher** [comment]
The core+drude particles are thermalized by the special bonds, so you can't use them with a global langevin thermostat. If you now want to simulate a Drude complex (like the IL from the drude_bmimpf6.py) PLUS some water, you need a way to thermalize the water as well. Therefore, you do the per particle thermalization to 'exclude' the Drude complex.

**Comment by jngrad** [comment]
Isn't it sufficient to simply set the Drude per-particle `gamma` to zero? Then the friction coefficient of Langevin is zero for Drude particles and non-zero for water molecules.

**Comment by KaiSzuttor** [comment]
then dissipation is zero but not fluctuation, right?

**Comment by KonradBreitsprecher** [comment]
Doesn't the gamma also appear in the variance of the random force?

**Comment by KaiSzuttor** [comment]
correct, @jngrad did you vheck if it works?

**Comment by jngrad** [comment]
Yes, sigma also appears as a prefactor of the random noise for Langevin. That's why the Langevin trajectories of Drude particles don't change regardless of the value of the per-particle temperature.
