### ISSUE TITLE
-lcuda needs to be removed for cuda-11.2

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4085]
At least in the installation done by spack, libcuda is not present, there is just libcudart.
This needs to be changed in cmake/FindCUDACompilerNVCC.cmake.
Don't know if -lcuda is needed for older cuda versions.

**Comment by mkuron** [comment]
libcuda.so is part of the driver, not part of the CUDA SDK. The driver is not installed on the headnode of our cluster because it does not have a GPU, so there is no libcuda.so. There is .../lib64/stubs/libcuda.so, which might be sufficient to link to. Generally, libcudart provides all the `cuda[A-Z][A-Za-z]+` functions and libcuda provices all the `cu[A-Z][A-Za-z]+` functions, so software like Espresso should not need to link to libcuda.
