### ISSUE TITLE
pypresso invalid interpreter for Spyder

### ISSUE THREAD

**Issue by marianoimperatore** [espressomd/espresso#4111]
pypresso (4.1.2) is reported as invalid interpreter for Spyder installed on my Ubuntu 20.04 LTS (Please see screenshot), differently from what said in the documentation http://espressomd.org/html/doc/index.html in section 2.6.3, although not present in the documentation for version 4.1.2 or 4.1.4 (the latest)
Does this means that it only works on the dev version? Is there a way I can make it work also in version 4.1.2?
![pypresso invalid spyder](https://user-images.githubusercontent.com/6430299/107399566-25e78000-6b01-11eb-8c7f-64e90784bd30.png)

**Comment by jngrad** [comment]
I think ESPResSo 4.1.2 should work, there was no major change to the `pypresso` script in 4.2-dev. It looks like a similar issue to the spyder bug on macOS (https://github.com/spyder-ide/spyder/issues/13252). I just tried it with spyder 4.2.1 and got a different error message, which is similar to the spyder bug on Windows (https://github.com/spyder-ide/spyder/issues/13996).

Since the `pypresso` script only sets the `PYTHONPATH` variable and the `spyder` script is a python script, you can launch spyder with `./pypresso $(which spyder)` and the interpreter will be able to import `espressomd`. I can confirm this works for ESPResSo 4.1.4 compiled for GPU with spyder 4.2.1. Once spyder gets a bugfix, you can try again setting the path in the IDE preferences.

**Comment by marianoimperatore** [comment]
Thank you very much jngrad, it works launching spyder with pypresso.
Btw, thank you very much guys for this amazing program!

**Comment by jngrad** [comment]
You're welcome!
