### ISSUE TITLE
Let reaction ensemble use observables/accumulators

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4156]
The reaction ensemlbe currently has its own "observables/accumulators", called collective variables.
It should instead use Espresso's observable and accumulator framework.
  
1. As a first step, the degree of association collective variable should be implemented as an observable in the sence of the observable framework.
In the first step, the observable can be stored in the collective variable struct of the RE and be evaluated, whenever the determin_current_state() method of the collective variable in RE is called.
Same can be done for the potential energy collective var.

2. In a second step, the minimum and maximum logic of the collective vars can be replaced by storing an accumulator in the collective var struct and have it calculate min/max/average.

3. In a final step, the Python ui can be modified, so the user can pass in any observable as a collective var.

the first two should be doable in a coding day.

**Comment by jngrad** [comment]
The `DegreeOfAssociationCollectiveVariable` behaves like an observable, but I'm not sure the `EnergyCollectiveVariable` does. The `EnergyCollectiveVariable` depends on the state of the Wang-Landau system. It's also unclear to me whether the minimum and maximum can be calculated from an accumulator, because the minimum and maximum of one collective variable depends on the minimum and maximum of all previously registered collective variables (I had a a surprise when unit testing a second collective variable: 76332ae4c0).
