### ISSUE TITLE
Add benchmark for MC methods

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#4209]
Akin to the MD benchmark scripts there should be a benchmark script for the MC methods, which measures the performance of a typical (=important to stakeholders) scenario, so that performance impacts introduced by changes can be identified, and to make
it possible for people without domain knowledge to identify bottlenecks.

**Comment by jonaslandsgesell** [comment]
I think a typical scenario would be the one in the reaction ensemble/cpH test with the reaction HA <> A +H. Typically A and H are charged. Not sure you want to benchmark with electrostatics though.
I would suggest parameters such that alpha is approx. 0.5 for the cpH test this would mean input1=pH=pK=-log10(Gamma)= input2
For the reaction ensemble alpha depends on the system volume and K so I would just choose those such that alpha approx 0.5 turns out (or compute it from the law of dilution).
N in 50...100 particles would be typical (as of 2019)

**Comment by jngrad** [comment]
This ticket is suitable for a coding day:
* choose the reaction method of interest among the scripts in `samples/`
* adapt the script using [`maintainer/benchmarks/lb.py`](https://github.com/espressomd/espresso/blob/python/maintainer/benchmarks/lb.py) as template
   * an overview on the benchmarking infrastructure is given in the [developer's guide](https://github.com/espressomd/espresso/wiki/Development#benchmarking)
   * the benchmark needs to run for anywhere between 40 seconds and 2 minutes
   * argparse:
      * option `--output` must stay, probably also `--particles_per_core` (has the number of particles an impact on Reaction Methods performance?)
      * other options can be removed
      * additional options can be added if they have a performance impact
* add a new line in [`maintainer/benchmarks/CMakeLists.txt`](https://github.com/espressomd/espresso/blob/python/maintainer/benchmarks/CMakeLists.txt#L99-L101) with input values that will make it run for anywhere between 40 seconds and 2 minutes
* write a test using [`testsuite/scripts/benchmarks/test_lb.py`](https://github.com/espressomd/espresso/blob/python/testsuite/scripts/benchmarks/test_lb.py) as template

**Comment by pm-blanco** [comment]
I will take care of this ticket tomorrow during the coding day.

**Comment by kosovan** [comment]
I plan to work with Pablo on that.
