### ISSUE TITLE
Nonbonded force kernel called if non-bonded cutoff is 0

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4293]
There was code at some point to skip the non-bonded kernel, when no nonbonded ia is present. This seems to ahve been removed.

**Comment by jngrad** [comment]
This is a regression introduced in 24b648ea3f1c64f7e53cf3df521a32a5f98f2792. For bonded interactions, we have to include zero since it's a magic value for angle and dihedral bonds: their range is zero, but they need to be evaluated. For non-bonded interactions, to get a range of zero we have to either manually set the cutoff to zero, or in the special case of WCA set sigma to zero; in either case the force/pressure/energy should be skipped since the potential is not physical (Dirac function).
