### ISSUE TITLE
Select Jupyter backend for the summer school

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4339]
* Jupyter
   * :heavy_check_mark: natively supports matplotlib
   * :heavy_check_mark: natively supports hidden solutions
   * :x: no code auto-completion
   * :x: no docstring integration: one has to lookup the user guide for function/class documentation
* Alternatives that support Jupyter notebooks:
   * [VS Code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)
   * [PyCharm](https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html)
   * [Spyder](https://docs.spyder-ide.org/current/plugins/notebook.html)

**Comment by biermanncarl** [comment]
I have messed around with VS Code and PyCharm and it seems that I can get a similar "amount" of autocompletion out of both of them. They both seem to struggle with compiled Cython libraries (like `espressomd.system`) and recognize only the existence of top-level entries (e.g. `espressomd.System`) but no details about them. The code completion works as expected for Python source code files like `accumulators.py`. This is disappointing, since we would like auto-completion to work for situations like `system.thermostat.<suggestions>`.

**Comment by biermanncarl** [comment]
`help(system)` works, however, and gives detailed information.

**Comment by biermanncarl** [comment]
After a day of investigation, it turns out that Jupyter simply is the best solution for us. In fact, it does the best job at almost all of our requirements. Autocompletion and docstring integration can both be obtained by activating the `Hinterland` extension that comes with `jupyter_contrib_nbextensions`. That extension also provides `Rubberband` and `Exercise2`, which we use for our tutorials anyway (for the hidden solutions). So in fact, many people at the institute will have this extension already installed. `Hinterland` also includes Cython docstrings, which none of the other options did.

Jupyter:
* Shows Cython docstrings (e.g. system)
* Does not show Python docstrings (e.g. accumulators)

VS Code:
* Mostly works.
* No support for the necessary nbextensions (solutions are not hidden).
* Problems with rendering LaTEX.
* Shows Python docstrings (e.g. accumulators)
* Does not show Cython docstrings (e.g. system)

PyCharm:
* Jupyter Notebook is only available in the Professional Edition, not in the Community Edition

Spyder:
* Unable to set pypresso as custom interpreter, for unknown reason

**Comment by biermanncarl** [comment]
In both Jupyter and VS Code, the hints that are not automatically shown can be brought up by executing `help(accumulators.Correlator)` (in Jupyter) or `help(espressomd.System)` (in VS Code).

**Comment by jngrad** [comment]
Thanks for looking into this. We will be using the Zoom + Jupyter combination.
