### ISSUE TITLE
Walberla: Support single precision on the CPU

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4378]
Since it has ~2x the performance and is commonly used for thermalized LB.

This involves the following steps:
* In `maintainer/walberla_kernels/`: generate single precision kernels in addition to double precision ones
* In `src/walberla_bridge/LBWalberlaImpl.hpp`: Make the Walberla floating type a template argument and make sure that float is actually supported. This will probably involve making the `to_vector3` and `to_vector3d` functions in the utility header function templates which work with float and double on the Walberla side.
* Add the possibility to instance LB with single precision in `src/walberla_bridge/lb_walberla_init.?pp` and `src/core/grid_based_algorithms/lb_walberla_init.?pp`
* Add the possibility to instance LB with single precision in `src/walberla_bridge/lb_walberla_init.?pp` and `src/core/grid_based_algorithms/lb_walberla_instance.?pp`
* Add a `float_precision="single"` or `"double"` to the LBWalberla class in `src/python/espressomd/lb.pyx`

**Comment by jngrad** [comment]
The waLBerla CMake logic provides a macro [`waLBerla_generate_target_from_python()`](https://i10git.cs.fau.de/walberla/walberla/-/blob/b17ca5caf00db7d19f86c5f85c6f67fec6c16aff/cmake/waLBerlaHelperFunctions.cmake#L39) to help generate the kernels as a dependency of another target. This is done via a codegen config string in json format that contains the list of kernels to generate and the waLBerla features. This could prove useful if we choose to let users generate the kernels themselves, with their own personal preferences regarding MPI+X. Here is what a such a configuration looks like:
```json
{
  "EXPECTED_FILES": [
    "generated_kernels/StreamSweep.cpp",
    "generated_kernels/CollideSweep.cpp",
    "generated_kernels/CollideSweepThermalized.cpp",
    "generated_kernels/InitialPDFsSetter.cpp",
    "generated_kernels/Dynamic_UBB.cpp"
  ],
  "CMAKE_VARS" : {
    "WALBERLA_OPTIMIZE_FOR_LOCALHOST": "OFF",
    "WALBERLA_DOUBLE_ACCURACY": "ON",
    "CODEGEN_CFG": "",
    "WALBERLA_BUILD_WITH_MPI": "ON",
    "WALBERLA_BUILD_WITH_CUDA": "OFF",
    "WALBERLA_BUILD_WITH_OPENMP": "OFF"
  }
}
```

This string is passed to the python codegen script and is parsed by the codegen context manager at line `with CodeGeneration() as ctx:`. We can read the information about single- or double-precision via `ctx.double_accuracy`.

Now, to the difficult part: when instantiating the `CodeGeneration` context, the class parses the json string from the python command line arguments via `sys.argv[1]` ([source code](https://i10git.cs.fau.de/walberla/walberla/-/blob/b123bc98bc7b3eacc316c8534a5824cfb18cc666/python/pystencils_walberla/cmake_integration.py#L56-61)), and generates a warning if it's not valid json. Not a deal breaker, but new users can easily waste time investigating the source of this warning if they don't know that it's harmless. This means that to use `argparse` in our codegen script, we need to do some additional work to guarantee that we don't take the conditional branch that emits the warning, and update that work every time we update the walberla commit in CMake. We could also overwrite the `CodeGeneration.context` member with our own `CodeGenerationContext` object that contains a dict with the double-precision information, but from what I understand this would be equivalent to directly replacing the `ctx` variable in the `with` statement (and again, we would need to update that workaround every time we change the walberla version).

Regarding code generation in single precision, there are a few flaws. For example, all numerical constants are written as `15.3` instead of `15.3f`, which leads to many `-Wfloat-conversion` warnings that will be converted to errors in CI. There are also a few rare examples of variables declared as `double const` in source files, and a few class members declared as `double` in header files, such as the 4 omega relaxation rates. I couldn't find whether these `double` came from a bug in the lbmpy/pystencils code, or from a missing keyword argument somewhere in 3687885435a05554.

In any case, the generated single-precision kernels will compile and work just fine with the current `LBWalberlaImpl` class. A few python LB tests fail due to precision errors in the order of 10^-7.

Regarding the `LBWalberlaImpl` support for floating point types: it currently uses `real_t` instead of `double` in class members and function signatures, except where necessary to receive/send data from/to the interface, which uses `double`.

I'm not sure if it is feasible to write `template <typename T> LBWalberlaImpl` and use that to instantiate single- and double-precision `LBFluidWalberla` objects, but I could be wrong. From what I understand, to use `LBFluidWalberla` in single precision, we need to recompile the entire walberla code in `_deps/` with `cmake . -DWALBERLA_DOUBLE_ACCURACY=OFF`, at which point it is impossible to instantiate `LBFluidWalberla` in double precision. To be able to use both with the same ESPResSo build, we would have to create two walberla build folders in `_deps/` with different values for `WALBERLA_DOUBLE_ACCURACY`, and hope that the linker will be able to resolve the symbols.

**Comment by jngrad** [comment]
The walberla branch now supports LB on single-precision: simply pass `single_precision=True` to the `LBFluidWalberla` class. The codegen script produces a few kernels with mixed `float`/`double` types. I wrote a basic text-substitution patch in the codegen script to handle a few of them (d9589957), and the remaining ones were either manually replaced or skipped via pragmas (2e1f076c). There are also a few areas that required manual patching to allow for unit testing (b0c19e49fe9c3). These issues were reported upstream in ticket [walberla/walberla#167](https://i10git.cs.fau.de/walberla/walberla/-/issues/167). As it turned out, many of the mixed types issues can be avoided by passing `data_type='float32'` instead of `data_type='float'` to kernel creation functions (python `float` become C++ `double`).

Regarding the performance of single-precision vs. double-precision, we first need to point out that on modern x86_64 archs `float` and `double` have similar performance for additions, subtractions and multiplications. Divisions and square roots are much slower with `double`, but since LB kernels don't do divisions (inverse constants are pre-computed), double-precision kernels should at least as fast as single-precision kernels in term of computational time, without vectorization. Benchmarking `Vector<T,3>` additions, subtractions and multiplications on `float` and `double` precision, with and without fast math optimization, reveals the following:

| workstation   | float  | double | ffmath float | ffmath double |
| :------------ | -----: | -----: | -----------: | ------------: |
| 64-bit seraue | 130    | 66     | 135          | 30            |
| 64-bit lama   | 135    | 68     | 137          | 30            |
| 64-bit alpaca | 135    | 69     | 140          | 31            |
| 32-bit laptop | 258    | 241    | 207          | 288           |

(time in milliseconds per loop, benchmark code: [main.cpp](https://github.com/espressomd/espresso/files/7522117/main.cpp.txt))

The single-precision kernels are as fast as the double-precision kernels on 1 MPI rank with small grid sizes. For large grid sizes the calculation is bandwidth-limited, and single-precision kernels become more attractive that double-precision kernels. For a grid size of 196x196x196, which takes 4GB of RAM with `double` vs. 3 GB of RAM with `float`, at 1 MPI rank the runtime is the same, at 4 MPI ranks `float` is 10% faster, at 8 MPI ranks `float` is 16% faster.

**Comment by RudolfWeeber** [comment]
This is still surprisingly little. 

Could you try with the stream-collide branch form my repo (this has one less communication per time step, so it should be faster in the first place, and also depend more on memory band with)

 

Probably, things will change again, once the upstream issues are fixed and we can turn on vectorization.

**Comment by jngrad** [comment]
Benchmark results for an unthermalized fluid on `-O3`, with or without `-ffast-math`, with `box_l` in {32, 64, 128, 196}:

![lb_benchmarks](https://user-images.githubusercontent.com/42201407/141804970-f8fa1c18-83e5-4539-9aa9-78ebefdb565a.png)
(Raw data: [benchmarks.csv](https://github.com/espressomd/espresso/files/7539544/benchmarks.csv), [benchmarks_plot.py](https://github.com/espressomd/espresso/files/7539548/benchmarks_plot.py.txt))


Here are the important points:
* the double-precision `walberla_stream_collide` implementation is faster than the double-precision `walberla` implementation with or without fast-math mode when at least 2 MPI ranks are used (solid lines)
* the single-precision kernels (dashed lines) are faster by 10-15% compared to double-precision kernels on 1 MPI rank, but this speed-up decreases to less than 10% at 8 MPI ranks or more
* there is a performance bottleneck at 8 MPI ranks for all grid sizes
* fast-math mode on single-precision is not momentum-conserving

**Comment by RudolfWeeber** [comment]
Do you have single precision results for the stream_collide version?

 

What would be the expected time, if the code was fully memory bandwith limited.

(Assuming three sweeps over the data per time step: 2x for stream, 1x for collide)

**Comment by jngrad** [comment]
> Do you have single precision results for the stream_collide version?

Unfortunately, no. I didn't understand from the diff what changed in the kernels, and the codegen script was unchanged. The two branches have diverged too much anyway (walberla patch, myconfig file, python interface). I was happy when it finally compiled.

**Comment by jngrad** [comment]
> The kernels are unchanged (for now), just the oreder is changed, and there is one communication less per time step.

ok then it's trivial, I just need to cherry-pick the commit for `src/walberla_bridge/LBWalberlaImpl.hpp` and discard the rest.

Although, is it safe to execute boundary handling before the rest? @reinaual's UBB patch required us to move dynamic UBB between the stream and collide steps. There are a few boundary-related LB tests that fail with your re-ordered time loop.

**Comment by RudolfWeeber** [comment]
Done, to my understanding

**Comment by jngrad** [comment]
Benchmark results for an unthermalized fluid on `-O3`, with or without AVX2, in single-precision and double-precision.

**Time per integration step**
Using single-precision is mostly beneficial with AVX2 enabled. Parallelization up to 4 MPI ranks significantly reduces runtime.
![plot_timing](https://user-images.githubusercontent.com/42201407/154261099-d32f0822-9bb3-46c6-bb4e-4657c4d20432.png)

**Relative speed-up**
Calculating the speed-up relative to double-precision on 1 MPI rank without AVX2. A plateau is reached at 8 MPI ranks.
![plot_speedup](https://user-images.githubusercontent.com/42201407/154261122-5ad84d9e-3cf5-4a5e-a3b6-d63757cc6343.png)

Raw data: [benchmarks.csv](https://github.com/espressomd/espresso/files/8079710/benchmarks.csv), [benchmarks_plot.py](https://github.com/espressomd/espresso/files/8079712/benchmarks_plot.py.txt)
