### ISSUE TITLE
Check lb_shear profile visually

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4400]
In the Walberla branch the node pressure tensor agreement with theory is not great and got even worse when updating to current lbmpy and walberla. Also, the velocity components perpendicular to the shear direction are far from zero (on the order of 1E-6). The profile produced by lb_shear.py needs to bexamined visually via vtk outputs. Particularly, if something odd happens at corners or edges.

Candidates for issues might be incorrect boundary handling in ghost layers.

**Comment by RiccardoFrenner** [comment]
I had a look at the VTK output, here is what I got:

I set `x` as the normal direction of the plane (`shear_plane_normal = (1, 0, 0)`)
and `y` as the shear direction (`shear_direction = (0, 1, 0)`).

In the following plots I looked at the velocity component in the x direction, which should ideally be zero.

The first image shows the surface of the whole box after 3 time steps. Although the velocity was zero in the previous time step, velocity components on the order of 1E-6 developed in the cells at a distance of `agrid` (`i_x=1`) from the planes. These develop and spread over the rest of the simulation, which is why it makes no sense to look at further time steps.
![velx_first_timesteps_whole_box](https://user-images.githubusercontent.com/76073356/149302746-c0df285e-99cb-4d41-8ddb-94f9a09b4339.png)
The second image shows these in more detail. A nonphysical pattern can clearly be seen, as the velocity oscillates from higher to lower values along the y-direction. The same can be seen for the pressure in the third image, where the second diagonal element of the pressure tensor is plotted. In this case, however, the cells right next to the planes (`i_x=0`) show the pattern.
![velx_first_timesteps](https://user-images.githubusercontent.com/76073356/149302844-dc4321ee-9578-4bd9-ac5a-6d58768e763a.png)
![press_4_first_timesteps](https://user-images.githubusercontent.com/76073356/149302875-02689a2e-a07a-4057-b219-017c0ac2894c.png)

I therefore think that the errors in pressure and velocity are related and would assume the boundary condition on the walls to be the source of the error.

**Comment by RudolfWeeber** [comment]
Thanks Riccardo. Is this homogeneous over the entire plane, or is there a more pronounced disturbance close to the edges or corners?

**Comment by RiccardoFrenner** [comment]
It is not homogeneous. In the first time steps it is just at the cells next to the planes. But then it spreads afterwards, but is still more pronounced close to the walls.

**Comment by RiccardoFrenner** [comment]
Sorry I think I misunderstood you. I think it is homogeneous over the plane, but I noticed something at the edges when I looked at the pressure tensor at the end of the simulation. I will post it right away.

**Comment by RiccardoFrenner** [comment]
This image shows the value at (0,1) of the pressure tensor. Two edges have significantly higher pressure than everywhere else.
![press_1_last_timesteps](https://user-images.githubusercontent.com/76073356/149324379-44ba88ef-8332-4c97-a2f6-0bde24dc15ec.png)
But since the pressure tensor value at (0,1) depends on `d/dy v_x` I think this can be related to the velocity values at the same places, since it is also very high, which I show here (`v_x`):
![velx_last_timesteps_whole_box](https://user-images.githubusercontent.com/76073356/149325185-a9d8d323-1c6f-4ce1-bb29-642517149c50.png)

So this is expected. And again, not sure how much can be said about these anyway, since the problems already arise in the first time steps.
Therefore I would say that the are no pronounced disturbance close to the edges or corners, just close to the planes.

**Comment by RiccardoFrenner** [comment]
I just increased the resolution of the domain. I can now clearly see pronounced disturbance at all corners of the domain in the z-direction of the velocity, but still not in the x-direction.
![velz_first_timesteps_high_res](https://user-images.githubusercontent.com/76073356/149333783-96a9660d-aca0-424f-975f-e9c5585a1048.png)
.

**Comment by RudolfWeeber** [comment]
Can you please check whether the ghost cells in all the edges and corners (i.e., when more than one coordinate is -1 or n), have the boundary flag and the boundary velocity set?

**Comment by RiccardoFrenner** [comment]
Is this possible to check in python or only c++/debugging?

**Comment by RudolfWeeber** [comment]
No, this is not exposed to Python. Probably the easiest way is to insert strategic printfs in the boundary node setters in the Walberla bridge..

**Comment by RiccardoFrenner** [comment]
They all have a velocity set but not all of them are boundaries. The planes with normal in y or z direction are not boundaries. But they have a velocity, which should not be the case, should it?

**Comment by RiccardoFrenner** [comment]
My bad, I retrieved the velocity with `get_node_velocity_at_boundary` not `get_node_velocity`. Before, every node had a velocity, now only those at the planes.

**Comment by RiccardoFrenner** [comment]
x indices go from -1 to 14 (including ghosts)
y indices go from -1 to 6 (including ghosts)
z indices go from -1 to 6 (including ghosts)

Nodes
13,  -1,  -1
13,  -1,   0
13,  -1,   1
13,  -1,   2
13,  -1,   3
13,  -1,   4
13,  -1,   5
13,  -1,   6
13,   0,  -1
are boundaries but have velocity zero. Every other node with x=13 has a velocity set, so this is definitely odd.
The opposite is the case on the other side. 
1,  -1,  -1
1,  -1,   0
1,  -1,   1
1,  -1,   2
1,  -1,   3
1,  -1,   4
1,  -1,   5
1,  -1,   6
1,   0,  -1
are not boundaries but have a velocity. Every other node with x=1 is not a boundary and has no velocity.

**Comment by RiccardoFrenner** [comment]
Also all nodes from -1, -1, -1 to -1, 6, 6 (the first plane slice of cells with normal in x-direction) and from 0, -1, -1 to 0, 0, -1 (L-shape of cells in z-direction) are boundaries but have no velocity.
This L-shape can also be seen in the velocity plots above I think.

**Comment by RudolfWeeber** [comment]
Can you please trace the boundary setup code to see why no velocity is set on that nodes. I guess, solving this will also remove the artefacts.

**Comment by RiccardoFrenner** [comment]
Sure.

**Comment by RiccardoFrenner** [comment]
Sorry, what I said above is wrong. The velocities and boundaries are actually set as expected. I just forgot to set `consider_ghosts` to true in `get_node_velocity`. The issue must be somewhere else then, maybe boundary handling?

**Comment by RiccardoFrenner** [comment]
I watched the z-component of the velocity at cell (0,0,0), which is one of the corners receiving a clearly visible disturbance on the order of 1E-8. The backtrace shows
```
#1 pystencils::StreamSweepDoublePrecision::run
#2 pystencils::StreamSweepDoublePrecision::operator()
#3 LBWalberlaImpl::integrate_stream
#4 LBWalberlaImpl::integrate_push_scheme
```
There is no boundary handling call listed. Then maybe it's not an issue of the boundary handling.

**Comment by RudolfWeeber** [comment]
Sorry, that’s not what I ment.

You traced the write access to the node, which happens during stream and collision.

The boundary condition is handled in a separate sweep (see the integrate()-function in the Walberla brdidge). The boundary handling will probably not even directly write to the cell but set up the neighbors such that the correct population will be streamed into the boundary node.

 

What I ment is following ghe code that sets up the boundary flag and velocity and make sure, it also sets the boundary and boundary velocity on the ghost cells, i.e., if 

0,0,0

Is a boundary,

N,n,n, 0,n,n, n,0,n

Need to be flagged as well.

I suspect this is not happening (at least for all relevant ghost cells)

**Comment by RiccardoFrenner** [comment]
> if
0,0,0
Is a boundary,
N,n,n, 0,n,n, n,0,n
Need to be flagged as well.

This is the case, at least when I can confirm this by calling `get_node_is_boundary(node, consider_ghosts=true)`. But I can try to confirm it in another way.

**Comment by RiccardoFrenner** [comment]
This has given me that every node with x = -1, x = 0, x = n-1or x = n is a boundary, and all others are not.
And since the planes are placed at x=0 and x=n-1, this should be correct.

**Comment by jngrad** [comment]
@RudolfWeeber Let's revisit this ticket again during the coding day. The pressure tensor off-diagonal terms are now much closer to the expected value in `testsuite/python/lb_pressure_tensor.py`, but  the diagonal terms are still a bit off.

**Comment by itischler** [comment]
I re-tested it today with the current branch and could not see any artifacts.
