### ISSUE TITLE
Missing feature guards in benchmarks

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4424]
when run via maintainer/benchmakrs/runner.sh, tests are run with default, maxset and empty myconfigs. However, some benchmarks rely on features not present in the empty myconfig. These need to skip without returning an error code, otherwise the "make benchmarks" fails and the benchmarking is interupted.

**Comment by jngrad** [comment]
Maybe we could leverage the CTest property [`SKIP_RETURN_CODE`](https://cmake.org/cmake/help/latest/prop_test/SKIP_RETURN_CODE.html) and return a magic error code from benchmarks that cannot run due to missing features, so that CMake prints "Skipped" instead of "Failed". If that doesn't work, we could instead look into [`SKIP_REGULAR_EXPRESSION`](https://cmake.org/cmake/help/latest/prop_test/SKIP_REGULAR_EXPRESSION.html#prop_test:SKIP_REGULAR_EXPRESSION). If both aren't possible, e.g. because CTest considers skipped tests as failures, I would be fine with returning 0 to mark the benchmark as passing (nothing will be written to the CSV output file).

I found other issues with the benchmark shell scripts last month and fixed them in a draft branch, so I would be happy to handle this ticket and add it to the pending changes.

**Comment by jngrad** [comment]
We cannot use a custom error code. Although python returns 1 for exceptions, it can also return any number between 2 and ~130 depending on which signal is sent, and the number of error codes keeps increasing with each release of python. MWE and output for python 3.9.7:
```
>>> import errno
>>> print(sorted(errno.errorcode.keys()))
[1, 2, ..., 131, 132]
```
For more details, see package [`errno`](https://docs.python.org/3/library/errno.html) for various python releases.
