### ISSUE TITLE
`non_bonded_loop_trace` seems to be broken

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#4432]
`system.cell_system.non_bonded_loop_trace()` doesn't seem to work properly. Given two particles in the system (`p0` and `p1`) it returns two entries for interactions `(0, 1)` and `(1, 0)`. Talking to @RudolfWeeber it seems that this function is supposed to only return one of these.
More importantly still, for certain combinations of `box_l` and particle positions one of the two distance vectors does not obey the minimum image convention. I observed this for a number of different position vector combinations, as an example see
```python
import numpy as np
import espressomd

box_l = 28.968631620212868
system = espressomd.System(box_l=[box_l, box_l, box_l])
system.time_step = 0.01
system.cell_system.skin = 0.4

p0 = system.part.add(pos=[14.276456611971197, 13.16738226901207, 8.927150084980797])
p1 = system.part.add(pos=[28.881982622730717, 0.39909834518046605, 7.269467872077882])

system.non_bonded_inter[0, 0].lennard_jones.set_params(
    epsilon=1, sigma=4, cutoff=10, shift=0)

system.integrator.run(0)

def obeys_mic(v):
    return np.all(abs(v) < box_l / 2)

# non_bonded_loop_trace_returns (id1, id2, pos1, pos2, vec21)
cs_pairs = system.cell_system.non_bonded_loop_trace()
print(cs_pairs, "\n")

# distance vectors via loop trace
core01 = cs_pairs[0][4]
core10 = cs_pairs[1][4]
# distance vectors from python
py01 = -system.distance_vec(p0, p1)
py10 = -system.distance_vec(p1, p0)

for vector in [core01, py01, core10, py10]:
    print(vector, np.linalg.norm(vector), obeys_mic(vector))
```
producing the following output
```bash
pkreissl@host:~/espresso/build$ ./pypresso minimal_mic.py 
[(0, 1, array([14.27645661, 13.16738227,  8.92715008]), array([28.88198262,  0.39909835,  7.26946787]), array([-14.60552601,  12.76828392,   1.65768221]), 0), (1, 0, array([28.88198262,  0.39909835,  7.26946787]), array([43.24508823, 13.16738227,  8.92715008]), array([-14.36310561, -12.76828392,  -1.65768221]), 0)] 

[-14.60552601  12.76828392   1.65768221] 19.470448755216818 False
[14.36310561 12.76828392  1.65768221] 19.289266119447404 True
[-14.36310561 -12.76828392  -1.65768221] 19.289266119447404 True
[-14.36310561 -12.76828392  -1.65768221] 19.289266119447404 True
```

**Comment by RudolfWeeber** [comment]
My current understanding is as follows.

When there are 2 physical cells per coordinate, we hae the following cell layout

```
g p p g
0 1 2 3 
``` 

where g stands for ghost cell and p for physical cell.
DomainDecomposition.init_cell_neighbors() sets up the following in the red_neighbors list of the cell, i.e., the one containing the upper half shell which is used for force/energy calculation.
```
1->2 2->3
```
However, 3 ist a ghost cell which has a copy of the content of 1.
This menas, effectively the cell pair (1,2) is considered twice during the short range loop (energy/force/pressure).

This does not lead to wrong energy/force results, because the domain decomposition implementation in Espresso does not use minimum image convention to calculae distances AND the positions of the particles in the ghost cells are shifted by one box length.
I.e. `pos_in_cell_4 =pos_in_cell_1 +box_length`.
So the extra pairs originating from traversiong `3->1` differ by one box length from the oens originating from traversing `1->2`. these pairs are then discarded either by the cutoffs of the individual interactions, either at the point of forcce/energy calcuaiton, or in case Verlet lists are used, at the time the Verlet lsits are created.

The `non_bonded_trace` at present does not perform this check, so the double pairs appear.

I find this situation intransparent and confusing. Simply removing the neighbor relationship `2->3` does not solve the issue, because then a particle at the very left of `1` and the very right of `2` would be too far apart to interact (sicne domain decomposition currently does not use minimum image convention to calculate distances).


The proper solution, IMO, is to use minimum image distance in DD AND remove the double neighborship. However, other algorithms in Espresso rely on the shifted ghost positions. LBCPU is definitely affected. For P3M and ELC it needs to be checked, whether ghost particles are considered.

**Comment by RudolfWeeber** [comment]
There may be more affected cases (in which no cutoffs are applied by the kernel). E.g., the random_pairs test fails if one sets the min_global_cut to box_l/2.
