### ISSUE TITLE
Tons of feature guards missing

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4560]
Starting from maxset, removing the following will cause compile errors:

* ELECTROSTATICS (in the script interface)
* DIPOLES (in the script interface)
* NPT (in the script interface)
* EXTERNAL_FORCEs (in virtual sites inertialess tracers due to missing ext_torque paritcel property, might requrie build with cuda)
* VIRUTAL_SITES_INERTIALESS_TRACERS (in script interface)

**Comment by jngrad** [comment]
I tried removing all of these features from maxset, and also removing them individually, but couldn't reproduce any compiler error. Did you use the python branch? Also it is worth noting that our file server has synchronization issues, for example `/work` is 6 seconds in the future since Monday, so if you modified the myconfig file and ran `make` less than 6 seconds later on an affected drive, the linker will link together object files that have been compiled with a different version of the myconfig file. It happened to me yesterday.

**Comment by RudolfWeeber** [comment]
The failling myconfig is:
`
```
#define ROTATION
#define ROTATIONAL_INERTIA
#define MASS
#define THERMOSTAT_PER_PARTICLE
#define LENNARD_JONES
#define VIRTUAL_SITES_RELATIVE
```

and related ones, with some of the featues listed in the initial issue added. This particular one doesn't compiel, others have undefined symbol when running.
