### ISSUE TITLE
engine_lbgpu test case fails with TRT

### ISSUE THREAD

**Issue by uschille** [espressomd/espresso#460]
As mentioned in #459, the engine_lbgpu test case fails after @rempferg and I fixed the relaxation and thermalisation of the ghost modes in the GPU LB. The fix changes parameters _only related to the ghost modes_, i.e., to first order the hydrodynamic limit should be unaffected. Nevertheless we observe significant differences in the flow field. Georg confirmed that a simple Stokeslet shows correct behaviour. So the differences in the test case are quite curious. I do not oversee where the engine features may be sensitive to the ghost modes. The only hypothesis I can come up with is that there is some peculiar interplay of the singular sources on short scales. It is still intriguing that this leads to such a pronounced difference. Any thoughts on this will be much appreciated.

**Comment by uschille** [comment]
@jdegraaf: Do you have any hint for us?

**Comment by jdegraaf** [comment]
Hello Ulf,

That's curious. What do you mean by  "significant differences in the flow
field"? Is the flow field of a single force-based swimmer with LB still
dipolar? I would say that changing the ghost modes should not affect the
viscous coupling scheme. Therefore, since the engine only uses the viscous
coupling and applies a force onto the fluid through the interpolation,
changing the ghost modes cannot change the method's behavior. LB is still
linear, so adding two point forces in close proximity, won't change that.
Since you are using TRT, are you using the same 'odd' and 'even' relaxation
parameter as in MRT? That's where I would suspect the problem lies. How did
Georg verify that "a simple Stokeslet shows correct behaviour"? By eye, or
by comparison to an analytic expression in PBCs? I would check the latter,
against his Stokes solver result. The swimmer I have simulated thus far
gave close-to-exact correspondence against the results of his Stokes
solver, so if you introduced a bug, or uncovered a bug that was cancelled
elsewhere, that result should no longer hold.

Best, Joost

**Comment by uschille** [comment]
Thanks Joost. I should have mentioned: In TRT we are using the 'odd' eigenvalue according to Irina Ginzburg that leads to a second-order accurate boundary condition (for grid aligned walls). The even ghost modes have the same relaxation as the stresses. So it is just a special case of MRT. When we set the relaxation parameter for the ghost modes to zero, the difference disappears. I don't have the numbers at hand right now, perhaps @rempferg can comment. I agree with you that changing the ghost modes should not change the behaviour - I am puzzled. We'll double check the Stokeslet tomorrow.

**Comment by rempferg** [comment]
A few of the relevant flow fields and particle positions and velocities are given in http://www.icp.uni-stuttgart.de/~georg/TRT.zip

The stokeslet produced by a single particle being dragged through a periodic box shows absolutely no difference between the current master and the TRT implementation. All test cases other than the engine_lbgpu.tcl pass. Results from the engine_lbgpu test case are given as flow fields and particle positions and velocities (every block a particle, 1st line position, 2nd line velocity). As you can see, the terminal particle positions and velocities are within 1% of each other. The flow fields, however, deviate by 50%. More precisely, the TRT is 50% faster and changes the shape of the flow slightly.

We ran those same tests setting all gammas to 0, making them all the same (BGK), making it a TRT, and using the TRT implementation but setting the ghost mode relaxation back to 0. The conclusion is that the engine_lbgpu test case produces the same result with the master and our current branch only of the ghost mode relaxation is zero, independently of everything else. We have no idea why.

We have only done before/after comparisons and didn't check against the stokes solver or analytical expressions. We can do that tomorrow, but I doubt that we will find anything unexpected, since I assume the old master to have matched those. Do you have a version of the stokes solver with the necessary swimmer infrastructure?

**Comment by uschille** [comment]
We shall also try to run the engine test with one source at a time. Perhaps it only shows up when there are multiple sources. A wild guess would be that the transformation of the ghost modes is buggy, which may never show up when they are projected out.

**Comment by jdegraaf** [comment]
Hi Guys,

The data Georg sent did not reveal anything to me. Could you run the
attached scripts with the following parameters with the TRT LB:

./espresso pnt_swimmer_entrain_LB_small.tcl puller 5.0 0.005
./espresso pnt_swimmer_entrain_LB_small.tcl puller 10.0 0.005
./espresso pnt_swimmer_entrain_LB_small.tcl puller 15.0 0.005
./espresso pnt_swimmer_entrain_LB_small.tcl puller 25.0 0.005
./espresso pnt_swimmer_entrain_LB_small.tcl puller 40.0 0.005

you'll have to modify the "outdir" path in the script and you can also
comment out all the vtk production (if you want), what I'm interested in
are the entrainment curves. It might take some time to run these (say half
a day each, or longer, depending on the machine), so use a fast machine. If
you can send me these, I can compare those to the original curves. Those
match both the Stokes solver result and the Ewald theory. So, if they no
longer correspond, you've broken something. Also, the 3D_dipole.py should
produce the same flow field as this swimmer, to which you could also
compare. To run it, you'll need to create a 'data' directory in the
directory in which the python script is located. Then run the
pnt_swimmer_... script: remove the entraining particle, pick a sufficiently
long time for the flow field to reach a steady state, and move the particle
(down) in such a way that at this time it is in the center of the box, to
facilitate comparison.

I hope this will help. Sorry I can't be of more use, I don't have access to
a proper computer full time yet, since apparently 8 months advance notice
of my arrival is not sufficient to draft a contract or get anything
administrative going.

Good Luck,

Joost

**Comment by rempferg** [comment]
I just realized I mistakenly ran the stokeslet tests on the CPU. There seems to be a difference if executed on the GPU. We are looking into that. Sorry for wasting your time.

**Comment by jdegraaf** [comment]
No problem, hope you managed to fix it.

**Comment by uschille** [comment]
@jdegraaf: When comparing to the Stokes solver and Ewald theory, what effective mobility did you use, i.e., what is the numerical renormalisation factor _g_?

**Comment by jdegraaf** [comment]
Hi Ulf,

I'm not sure if I follow, do you mean the mobility of a tracer particle or
of the stokeslet/doublet? What experiment are you running?

Joost

**Comment by uschille** [comment]
I'm referring to the difference between the effective friction and the bare friction in the LB viscous coupling. Perhaps I'm a bit confused, because I don't know exactly what you did in the Stokeslet tests. I'll have a close look at the scripts.
