### ISSUE TITLE
Python system interface lets user set properties that don't exist

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#569]
The following should notify the user that system has no property thispropertydoesnotexist. Instead it quietly keeps going:

import espressomd._system as es
import espressomd

system = espressomd.System()
system.thispropertydoesnotexist = 0.001

**Comment by rbardak** [comment]
that's because `espressomd.System` is a python class which inherits from the cython class `System` defined in `_system.pyx`. 

This means espressomd.System has a dynamic `__dict__` for its attribute list. This implies that `system.thispropertydoesnotexist = 0.001` is the same as `system.__dict__["this..."] = 0.001`, which is valid python code.

I don't understand why we have to wrap the cython class System, defined in espressomd/_system.pyx with the python class System, defined in espressomd/system.py in the first place. We don't really get any benefit from that, since we can still import cdef classes as extension types without the need of wrapping them. 
If we were to use the cython class directly, then we would get a runtime error if we tried to set properties which do not exist, therefore solving this issue.

**Comment by RudolfWeeber** [comment]
I think that this was done at some point due to the way the mpi .so
was loaded. It might not be needed any more.

**Comment by rbardak** [comment]
Here are two solutions to the problem.

The first one has no loopholes and is not runtime dependent, but it sets a limitation to the system class. With this fix, we have to require that all attributes of the system class need to be defined at class level. That means if a method sets a new attribute, it needs to be declared first. The limitation only affects the development process for the system class and right now does not have any impact on its functionality.

The second solution relies on the inspect module. It determines in what context `__settattr__` was called. If `__setattr__` is called within a method of the class, then allow the definition of new attributes (eliminating the limitation in the first solution). If `__setattr__` is called in any other context, only allow it if the attribute is already known. This solution has a loophole: if the caller of `__setattr__` has the same name as a method of System, then it also allows full access to the instance. It is also very inelegant and prone to failure, because we look at the stack to determine the context.

**Comment by RudolfWeeber** [comment]
> The first one has no loopholes and is not runtime dependent, but it sets a limitation to the system class. With this fix, we have to require that all attributes of the system class need to be defined at class level. That means if a method sets a new attribute, it needs to be declared first. The limitation only affects the development process for the system class and right now does not have any impact on its functionality.
I'd be fine with that solution

**Comment by fweik** [comment]
I'm not totally sure that this is a problem in the first place. Isn't that
part of what we wanted with python?
I mean that is the python way, if we do not want that we should use a
strongly typed language.
I suppose your problem is that you would not notice typos?

On Thu, Mar 24, 2016 at 4:23 PM, RudolfWeeber <notifications@github.com>
wrote:

> > The first one has no loopholes and is not runtime dependent, but it sets
> a limitation to the system class. With this fix, we have to require that
> all attributes of the system class need to be defined at class level. That
> means if a method sets a new attribute, it needs to be declared first. The
> limitation only affects the development process for the system class and
> right now does not have any impact on its functionality.
> I'd be fine with that solution
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/espressomd/espresso/issues/569#issuecomment-200884497>
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by rbardak** [comment]
I agree with Flo. Having full control over an object is basically a language feature of python.

Then again limiting control over System may lower frustration with unexpected behaviour and inhibits a user's ability to provoke segfaults with unorthodox use cases.

**Comment by RudolfWeeber** [comment]
> I agree with Flo. Having full control over an object is basically a language feature of python.
> 
> Then again limiting control over System may lower frustration with unexpected behaviour and inhibits a user's ability to provoke segfaults with unorthodox use cases.
I think allowing this will lead to a lot of users shotting
themselves into the foot due to mis-spelled attribute names.

If we do not restrict the creation of custom attributes, weh should
move the setting of md variables (time_step, box_l) to a setter
function which takes a dictionary or keyword arguments and checks
that only valid keys are given.
I.e.
S.set(time_Step=0.01,box_l=(10,10,10))

Maybe that is anyway the better solution?

**Comment by rbardak** [comment]
> move the setting of md variables (time_step, box_l) to a setter

I like the idea of an alternative safe-to-use function. This would not affect the way we set md variables now, but would provide a saner alternative. Also it provides the possibilty of setting up a system by passing a dict instead of setting attributes by hand, which would provide more flexibility for automated scripts.

**Comment by arnolda** [comment]
Hi guys!

Are you aware that this breaks inheritance from the System object? Child classes cannot have attributes of their own, and this also breaks for example most Python mock implementations.

E. g. this fully sensible example will break:

class CubicSystem(espressomd.System):
  def __init__(self, symbox_l):
    super(MySystem, self).__init__()
    self.symbox_l = symbox_l
    self.box_l = [self.symbox_l] * 3

If you want to prevent users from setting the wrong values, don't let them set attributes, rather use explicit setters/getters for each attribute.
