### ISSUE TITLE
Building on travis is slow

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#613]
and building in general is slow (I'm working on that.). I suggest that we split build tests and make check
and run the tests only with one compiler. After all, we're not hunting compiler bugs.

**Comment by RudolfWeeber** [comment]
Can this be closed?

**Comment by mkuron** [comment]
No, this isn't fixed yet.

**Comment by hmenke** [comment]
What is the exact task here?  Do you want to always build unit tests but run them only on one compiler, or do you want to build and run tests only on one compiler?

**Comment by mkuron** [comment]
He meant the former. Though we still need to run the tests once with Python 2 and once with Python 3 on both Mac and one Linux platform to ensure that all the linking etc. works.

Since we are actually primarily running different myconfigs now and not different compilers, I think this issue can now be closed. The only duplication is that we run myconfig=maxset with both Debian and Ubuntu since these are very popular distributions (perhaps we should even add CentOS and openSUSE, which are popular too and are very common in HPC environments).

**Comment by hmenke** [comment]
I agree that CentOS and openSUSE are valid build targets, however, I think we are already wasting more than enough build minutes.  Travis should convert this directly to CO2, so users can see the impact.
