### ISSUE TITLE
H5MD should be implemented in the core.

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#673]
To efficiently write trajectories with the hdf5 library in the H5MD format its necessary to have the respective function in the core.

**Comment by jonaslandsgesell** [comment]
Anyway this would be the clean way. Otherwise one has to maintain two h5md implementations (one in tcl and one in python). I like the idea more to have one C implementation.

**Comment by fweik** [comment]
Yes and somebody should use the c++ bindings of hdf5, and the particle
writer should be abstracted away anyway, and ...

**Comment by jonaslandsgesell** [comment]
Last time I looked the hdf5 cpp library was deprecated.

**Comment by fweik** [comment]
That one? https://www.hdfgroup.org/HDF5/doc/cpplus_RM/index.html

Does not look that way.

**Comment by jonaslandsgesell** [comment]
Well at least (in the past) the deprecating was a reason for this h5md cpp module that supports parralel IO. There is still a comment about it on this page:
https://github.com/h5md/h5xx/blob/master/README.md
Maybe we could also use this h5xx wrapper.

**Comment by fweik** [comment]
You are talking about h5md, I am talking about hdf5

On Tue, Jun 14, 2016 at 8:59 AM, Jonas Landsgesell <notifications@github.com
> wrote:

> Well at least (in the past) the deprecating was a reason for this h5md cpp
> module that supports parralel IO. There is still a comment about it on this
> page:
> https://github.com/h5md/h5xx/blob/master/README.md
> Maybe we could also use this h5xx wrapper.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/issues/673#issuecomment-225795848>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2i3_wQmc1vgInGamCsVkSvyYbQyu3eks5qLlFXgaJpZM4I0aTn>
> .
>



-- 
Florian Weik

florianweik@gmail.com
++49 157 85939252

**Comment by fweik** [comment]
Ok, h5xx looks great. Maybe we should use that.

**Comment by KaiSzuttor** [comment]
I once wondered what is the clean way to use such an external library. Include it into the espresso project as a submodule (thats what @mkuron came up with).

**Comment by fweik** [comment]
I think submodules and cmake ExternalProject is the modern way. The one had to put the source into the release tarballs. That is if we want to offer conventional releases in the future. Other ways is to just check in the source, which is bad because it could diverge. Gromacs offers the possibility to download and build  FFTW at configure time, but I can't see any benefit of that over submodules. We have to come up with a solution for that soon anyway, because we're going to depend on libpfft, for which no distribution packages exists to my knowledge.

**Comment by KaiSzuttor** [comment]
Maybe I'm missing something but it looks that @hirschsn is working on a parallel trajectory writing in the /src/core/mpiio.cpp. Isn't that reinventing the wheel, if we want to use the H5MD binary format in the future?

**Comment by pdebuyl** [comment]
Hi,

I don't know the current espresso architecture well but I have experience in writing H5MD code, so I have a few comments.

1. The C++ interface is not *really* interesting. I never tried it but the reference HDF5 interface is the C one. The C++ interface might not be compiled by default on every platform (so, one source of negative user experience) and it has less usage, so probably more bugs.
2. There is a very basic C library for H5MD that I wrote https://github.com/pdebuyl/ch5md and used to implement a H5MD writer in LAMMPS http://lammps.sandia.gov/doc/dump_h5md.html It is all serial, though.
3. One possible way to bundle HDF5 is as I have done in my personal simulation code: 
https://github.com/pdebuyl-lab/RMPCDMD/blob/master/scripts/download_and_build_hdf5.sh is a script to download and build hdf5 (here with the Fortran 2003 bindings that are typically missing). Then, one can simply point CMake to it via the environment variable HDF5_ROOT (see http://lab.pdebuyl.be/rmpcdmd/install.html#install-hdf5 )

All of this might be impractical for espressomd but I hope it helps anyway. Let me know if you would like more information.

Pierre

**Comment by KaiSzuttor** [comment]
Thanks @pdebuyl for your comments. Regarding the C++ interface, I think you are right, we could also stick to the more low-level hdf5 C library without having an additional dependency to that h5xx library without having much more code to write. I think the C functions you used for the LAMMPS implementation is a good starting point for us. Regarding your third comment, I think most of the current Linux distributions come with a hdf5 library in their official repositories, at least:
- debian [https://packages.debian.org/search?keywords=hdf5&searchon=names&suite=stable&section=all]
- openSuse [https://software.opensuse.org/package/libhdf5-10]
-  ubuntu [http://packages.ubuntu.com/search?keywords=hdf5&searchon=names&suite=xenial&section=all].

**Comment by fweik** [comment]
Thank you for your input. I still have the feeling that there should be a high level c++ library for h5md (not just library bindings for hdf5). Maybe something like this should be started, because many md packages and tools could benefit from that, and it would of course help to spread h5md, which is  most useful if it is widely spread. (Unfortunately the Gromacs project manager told me recently that they don't want to adapt hdf5/h5md because they don't want to introduce additional dependencies and they claim their own format has better compression properties for trajectories.)

Regarding Espresso, we should have the file format abstracted away anyhow (think class ParticleWriterBase), this would make it less problematic if there is an implementation that contains all the low level hdf5 stuff.

**Comment by KaiSzuttor** [comment]
Regarding the abstraction we should have a look into the object oriented and quite active developed MDAnalysis code (although in python the ideas might be adoptable to our problem):
[https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py](mdanalysis)

**Comment by pdebuyl** [comment]
Hi @KaiSzuttor, on the Mac the situation is a bit annoying with respect to HDF5 (build errors, no default Fortran compiler, macports did not find the package). Also, I need to enable the Fortran 2003 interface that is not found in Ubuntu 14.04 LTS for travis.

@fweik a higher level C++ library involve design choices for the access of array data that can be different from project to project. That remains a project-specific question, thus, and I have no personal C++ project. In espressopp I did experiments at the Python level using https://github.com/pdebuyl/pyh5md including parallel io (see @MrTheodor work here https://github.com/espressopp/espressopp/pull/52 ). Parallel i/o would benefit from tuning (ahem).

Finally, for lammps, the specific "USER-H5MD" code is mostly typical lammps boilerplate on top of ch5md.

Sorry for the flood of info!

**Comment by jonaslandsgesell** [comment]
What's wrong with including h5xx from felix @fhoefling?
Seems pretty easy to use.

**Comment by fhoefling** [comment]
Thanks, Jonas for pointing at the h5xx library. 

The goal of the h5xx library was to make HDF5 access as easy as h5py, at least for standard operations with the ability to use the low-level API for fine-grained tuning stuff. It has nothing to do with the unwieldy and not very helpful HDF5 C++ API. In fact, we have fully refactored h5xx to abandon any dependence on the "official" C++ API.

If you want to use h5xx in Espresso, you may simply add it as a (git) submodule. It has header files only, so you can also copy the files and ship them with Espresso. (We use the BSD license now.)

Regarding H5MD: in principle, you can write the H5MD files directly from your Espresso code without an additional layer for H5MD. h5xx makes this particularly simple. Still, such a (small) layer could be useful to ensure compatibility with the H5MD specification (metadata, H5MD "elements", certain required attributes, ...)

Felix

**Comment by pdebuyl** [comment]
Hi @fhoefling  :-) Should the data be stored in boost containers or arrays for use with h5xx?

**Comment by mkuron** [comment]
@pdebuyl: HDF5 on the Mac installs just fine for me. First, check which OpenMPI version you have installed:
```
port installed openmpi*
```
If you see `openmpi-default`, use
```
sudo port install hdf5 +openmpi +gfortran -cxx
```
If you have `openmpi-gccXX`, use
```
sudo port install hdf5 +openmpi +gccXX -cxx
```

**Comment by fhoefling** [comment]
So far, we have implemented support for std::vector, boost::array, and boost::multi_array. But this can be extended almost instantaneously.

A somewhat more flexible approach would be adding an iterator interface (restricted to contiguous data).

**Comment by hirschsn** [comment]
@KaiSzuttor I added MPI-IO earlier this year because we needed an efficient way to dump simulation data in parallel. Back then I was unaware that there were thoughts of going parallel with the HDF5 functionality in ESPResSo (or maybe they hadn't come up back then). The MPI-IO implementation can only be used to dump arrays (of particle types, positions, velocities and bonds, though, others can be added quite easily). Basically, every array is written to an own file which makes it easy to read the simulation data in external programs (see tools/mpiio2blockfile.py) without needing any dependencies.
Although I don't know HDF5 and H5MD I think that an abstract parallel output might be worth implementing to minimize the overhead of dumping other simulation data and making use of (hopefully machine-specific/optimized) IO libraries.

**Comment by KaiSzuttor** [comment]
@hirschsn I began implementing the H5MD functionality in my repo [https://github.com/KaiSzuttor/espresso/tree/h5mdcore](h5mdcore). Since I'm not experienced in writing mpi-parallel code, you may wont to comment on my implementation (and maybe add parallelization). That is maybe something a lot of people could benefit from.

**Comment by KaiSzuttor** [comment]
#745

**Comment by jonaslandsgesell** [comment]
H5MD in the core only with python interface is merged now.

**Comment by fhoefling** [comment]
body { font-family:'DejaVu Sans'; font-size:14px}

Thanks, Jonas, for putting your effort in this! I'm happy to see that H5MD is useful for you and that it is now even part of the ESPResSo core.Best wishes,FelixOn Tue, 29 Nov 2016 08:17:08 +0100, Jonas Landsgesell <notifications@github.com> wrote:H5MD in the core only with python interface is merged now.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/espressomd/espresso","title":"espressomd/espresso","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/espressomd/espresso"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jonaslandsgesell in #673: H5MD in the core only with python interface is merged now."}],"action":{"name":"View Issue","url":"https://github.com/espressomd/espresso/issues/673#issuecomment-263494859"}}}
