### ISSUE TITLE
Structure the code

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#764]
It would be very helpfull for new developers if the code would be more structured, i.e. Have subdirs in src/core and src/python.
E.g. I've done it in the h5mdcore PR.

**Comment by fweik** [comment]
I think the structure should be as follows: We should have a namespace at least per logical part of the code, and the folder structure should reflect the namespace structure. Eg. the h5mdcore resiedes in [Espresso::]Core::IO:H5MD, and the files can be found in 'core/io/h5md/'.
A unique top-level namespace is typically used (this makes name collision extremely unlikely).

We should
- Decide on a scheme
- Document it somewhere

**Comment by rbardak** [comment]
I agree, this has been bugging me since always. As Flo has suggested with h5md, I support the notion of creating multiple layers of subdirs. This makes it substantially easier to identify independent parts of the code.

In addition to structuring the files according to the logical structure in the code, I believe it is also helpful to structure according to `#ifdef`s in `myconfig.hpp`. If the majority of a files' code is specific for a single `ifdef`, then either
a) introduce an additional layer of subdirs
or b) use a filename which satisfies a naming convention

An example for both solutions would be LB:
either
a) `src/core/Actor/lb/lb_boundaries/...`
or
b) `src/core/Actor/lb/lb_boundaries.cpp`

In this specific case I would prefer b), since creating an extra folder for 2 out of 6 files actually adds obscurity. The usefulness of the (micro-)structure doesn't outweigh the ease of navigation.

As for the documentation, I've pitched the idea countless times: a developers' guide which covers the core functionalities and infrastructure of espresso. I would actually be willing to work on that, however I don't want to do that alone as I am not familiar with all aspects of espresso's infrastructure.

**Comment by fweik** [comment]
What Robin says makes it also easier to exclude code from the build if it is disabled.

**Comment by rbardak** [comment]
While we're at it, should we get rid of some file globs in our build system and explicitly add files? Is the additional control beneficial? It wouldn't be too much of an additional effort considering that we would need to write a bunch of new CMakeLists anyway.

**Comment by fweik** [comment]
Please have a look at https://github.com/espressomd/espresso/wiki/Naming-conventions-and-folder-structure

**Comment by rbardak** [comment]
I agree with everything so far, however adapting the namespace convention to all of the existing code might at best double the workload, at worst give us nasty suprises. When restructuring, at first maybe limit the namespace convention to (from a developer's point of view) important code.

Also, I can edit the wiki without making pull requests, I assume that wasn't intentional.

**Comment by fweik** [comment]
Who said anything about restructuring existing code? :-) You can because you are part of the Espresso Team. This is intended. (Also it is of coarse a git repo, so the damage you can do is limited.)

**Comment by KaiSzuttor** [comment]
Actually I don't see the point in naming private variables differently? What is the benefit here?

**Comment by rbardak** [comment]
I think the benefit is that you don't have to constantly check the header file in order to figure out if something is private or public when reading implementation code.

**Comment by fweik** [comment]
It improves readability if you can see if something is a data member or a parameter.
Now you can either use this-> everywhere or use something like _private_member or private_member_ . The first one is more characters and can be ommited, and I find' the underscore thing extremely ugly. Also _private_member is not valid in certain contexts. So m_ it is (for my, but "adapted" for non CamelCase). (It is understood that in good code there are no globals and no public data members of course...)

**Comment by RudolfWeeber** [comment]
Splitting the src/core directory I find worthwhile. 
I find it important, not to overdo it, though. One hierarchy-level should be enough to improve readability considerably:
E.g.
core
  non_bonded
  bonded
  long_range
  io
  constraints
or something like that. 
If there are 3 levels as in long_range/magnetostatics/p3m/py3m_magnetic.cpp it would in my opinion make things more difficult rather than easier.

I'd by very hesitant with subdirs on the python side, as this is visible to the end user. While a strucutre could be partially applied on the c++ side, for the python interface it should be all or nothing. It'd be very confusing, if, say, p3m is in the long_range subdirectory and ewald isn't.
