### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#874]
We agreed on the last Espresso Dev meeting that we should improve the documentation to help
people to contribute to Espresso. The developers guide, that is currently part of the Espresso
documentation is horribly outdated (really, there is virtually no part in it that reflects the current
state of affairs) and should be removed. We agreed to add pointers to the proper docs to the Readme,
the build instructions and the webpage. 

The question is now where this new and to be written docs should reside. Possibilities are to keep
them in the Espresso repo in some form, in the developer wiki on the webpage (yes, that exists) or
as a wiki on github.

Any opinions?

**Comment by rbardak** [comment]
Concerning the webpage wiki, it seems to be physically the farthest thing from the actual development process. It's almost hidden on the webpage, which itself is not really related to the actual development process. As for the Github wiki, it's something people might run into when they are making their first pull requests, which is far too late. 

It should be kept in one place, otherwise it would be a hassle to both maintain and contribute to these docs. The Espresso repo sounds like a good idea, since everybody who is developing for Espresso is bound to have a copy of the guide, independent of whether or not they are aware that it exists. We could put some kind of message at the end of the build summary of cmake, which would implore everyone who tries to build from the git repo to consult the 00-tutorial and the developers guide.

**Comment by RudolfWeeber** [comment]
I find wikis much preferrable to some tex-file.
We can just keep using the one on espressomd.org. Otherwise we would have two, which we would have to merge.
Regarding visibility, a link can be added to the readme.md on github.
