### ISSUE TITLE
TCL/Python split

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#882]
To recap what we want to do:
1. Remove python support from the current master
2. Rename the master to tcl
3. Rename python to master
4. Remove TCL from the master
5. cherry-pick commits since split from tcl to master

I am going to do this tomorrow if there is no objection.

**Comment by RudolfWeeber** [comment]
> 1. Remove python support from the current master
> 2. Rename the master to tcl
> 3. Rename python to master
> 4. Remove TCL from the master
You can make use of #873 for the tcl removal

**Comment by mkuron** [comment]
I've thought about this for a bit more and think that, at the very least, we need to set a policy stating what kinds of changes to the tcl branch will be accepted from here on. Critical bugfixes only, any new features, something in between?

Also, I am concerned about what happens if the branches diverge quickly and we find a critical bug that affects both. We might end up needing to fix the same bug twice. If that happens more than once or twice, perhaps adapting the tcl interface to the new boundaries code would have been easier.

**Comment by RudolfWeeber** [comment]
> I've thought about this for a bit more and think that, at the very least, we need to set a policy stating what kinds of changes to the tcl branch will be accepted from here on. Critical bugfixes only, any new features, something in between?
Since it has been visible for a time that the trnasition is
happening, I'd only accept important bug fixes.

If important features appear, we can help with developing a python
interface. In most cases, writing the Python interface is much less
work than writing a tcl interface.


> Also, I am concerned about what happens if the branches diverge quickly and we find a critical bug that affects both. 
This certainly is an issue. I'm not sure, however, we are in a
position to make promises about bugfix releases in the first place.
For the next half year or so, it's probably not an issue, because
enough active developers still have projects going, using the tcl
version, and therefore have a personal interest in fixing things.


> We might end up needing to fix the same bug twice. If that happens more than once or twice, perhaps adapting the tcl interface to the new boundaries code would have been easier.
It is not only boundaries (which has a lot of similarities with
constraints, which is already there). There are also 2600 lines of
tcl interface code for the observables  and correlators, which would
need major refactoring. 

I personally would see more productive uses of the development time
I'm able to invest, in other tasks, like quality assurance and
documentation for the Python interface.
