### ISSUE TITLE
cuFFT native memory layout removed in cuda 8.0

### ISSUE THREAD

**Issue by rempferg** [espressomd/espresso#918]
We need to switch to the FFTW memory layout in EK and P3M_GPU.

**Comment by mkuron** [comment]
`CUFFT_COMPATIBILITY_NATIVE` has been deprecated since CUDA 6.5 and apparently broken under some conditions since CUDA 7.0, before it was removed in CUDA 8.0. See https://devtalk.nvidia.com/default/topic/896719/apparently-bug-in-cufft-of-cuda-7-5-with-deprecated-native-compatibility/, https://github.com/mumax/3/issues/52, and many others. Have we seen any weird results with FFTs in the past two years?
